SET IDENTITY_INSERT [dbo].[Modules] ON
INSERT INTO [dbo].[Modules] ([MODULE_ID], [NAME]) VALUES (1, N'Application Maintenance')
INSERT INTO [dbo].[Modules] ([MODULE_ID], [NAME]) VALUES (2, N'Monthly Admissions/Surgeries Tracking')
INSERT INTO [dbo].[Modules] ([MODULE_ID], [NAME]) VALUES (3, N'Strategy')
INSERT INTO [dbo].[Modules] ([MODULE_ID], [NAME]) VALUES (4, N'Providers')
INSERT INTO [dbo].[Modules] ([MODULE_ID], [NAME]) VALUES (5, N'Capital Budget')
INSERT INTO [dbo].[Modules] ([MODULE_ID], [NAME]) VALUES (6, N'Income Guarantees')
INSERT INTO [dbo].[Modules] ([MODULE_ID], [NAME]) VALUES (7, N'Decision Support Reporting')
INSERT INTO [dbo].[Modules] ([MODULE_ID], [NAME]) VALUES (8, N'Employed Providers')
INSERT INTO [dbo].[Modules] ([MODULE_ID], [NAME]) VALUES (9, N'Service Survey')
INSERT INTO [dbo].[Modules] ([MODULE_ID], [NAME]) VALUES (10, N'Operational Improvements')
INSERT INTO [dbo].[Modules] ([MODULE_ID], [NAME]) VALUES (11, N'Primary Care Strategy')
INSERT INTO [dbo].[Modules] ([MODULE_ID], [NAME]) VALUES (12, N'PCR')
INSERT INTO [dbo].[Modules] ([MODULE_ID], [NAME]) VALUES (13, N'Chest Pain Registry')
INSERT INTO [dbo].[Modules] ([MODULE_ID], [NAME]) VALUES (14, N'Can Add New Employed Providers')
INSERT INTO [dbo].[Modules] ([MODULE_ID], [NAME]) VALUES (15, N'OP No Show')
SET IDENTITY_INSERT [dbo].[Modules] OFF
