CREATE TABLE [dbo].[APPLICATION_SETTING] (
    [APPLICATION_SETTING_ID] INT          IDENTITY (1, 1) NOT NULL,
    [NAME]                   VARCHAR (50) NOT NULL,
    [VALUE]                  VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_APPLICATION_SETTING] PRIMARY KEY CLUSTERED ([APPLICATION_SETTING_ID] ASC)
);

