CREATE TABLE [dbo].[BudgetThreeYearTotal] (
    [THREE_YEAR_TOTAL_ID] INT IDENTITY (1, 1) NOT NULL,
    [PDTS_PROVIDER_ID]    INT NOT NULL,
    [BUDGET_YEAR]         INT NOT NULL,
    [SURGICAL_TYPE_ID]    INT NOT NULL,
    [INPATIENT_TOTAL]     INT NOT NULL,
    [OUTPATIENT_TOTAL]    INT NOT NULL,
    CONSTRAINT [PK_BudgetThreeYearTotal] PRIMARY KEY CLUSTERED ([THREE_YEAR_TOTAL_ID] ASC),
    CONSTRAINT [FK_BudgetThreeYearTotal_Provider] FOREIGN KEY ([PDTS_PROVIDER_ID]) REFERENCES [dbo].[Provider] ([PDTS_PROVIDER_ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_BudgetThreeYearTotal_Surgical_Type] FOREIGN KEY ([SURGICAL_TYPE_ID]) REFERENCES [dbo].[Surgical_Type] ([SURGICAL_TYPE_ID])
);

