CREATE TABLE [dbo].[CARDIAC_BIOMARKER_TYPE] (
    [CARDIAC_BIOMARKER_TYPE_ID] INT          IDENTITY (1, 1) NOT NULL,
    [NAME]                      VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_CARDIAC_BIOMARKER_TYPE] PRIMARY KEY CLUSTERED ([CARDIAC_BIOMARKER_TYPE_ID] ASC)
);

