CREATE TABLE [dbo].[CHEST_PAIN_FIBRI_NOT_GIVEN_REASON] (
    [CHEST_PAIN_FIBRI_NOT_GIVEN_REASON_ID] INT           IDENTITY (1, 1) NOT NULL,
    [NAME]                                 VARCHAR (100) NOT NULL,
    CONSTRAINT [PK_CHEST_PAIN_FIBRI_NOT_GIVEN_REASON] PRIMARY KEY CLUSTERED ([CHEST_PAIN_FIBRI_NOT_GIVEN_REASON_ID] ASC)
);

