CREATE TABLE [dbo].[CHEST_PAIN_PATIENT_MEASURE] (
    [CHEST_PAIN_PATIENT_MEASURE_ID] INT            IDENTITY (1, 1) NOT NULL,
    [CHEST_PAIN_PATIENT_ID]         INT            NOT NULL,
    [CHEST_PAIN_MEASURE_ID]         INT            NOT NULL,
    [RESULTS]                       DECIMAL (5, 2) NOT NULL,
    CONSTRAINT [PK_CHEST_PAIN_PATIENT_MEASURE] PRIMARY KEY CLUSTERED ([CHEST_PAIN_PATIENT_MEASURE_ID] ASC),
    CONSTRAINT [FK_CHEST_PAIN_PATIENT_MEASURE_CHEST_PAIN_MEASURE] FOREIGN KEY ([CHEST_PAIN_MEASURE_ID]) REFERENCES [dbo].[CHEST_PAIN_MEASURE] ([CHEST_PAIN_MEASURE_ID]),
    CONSTRAINT [FK_CHEST_PAIN_PATIENT_MEASURE_CHEST_PAIN_PATIENT] FOREIGN KEY ([CHEST_PAIN_PATIENT_ID]) REFERENCES [dbo].[CHEST_PAIN_PATIENT] ([CHEST_PAIN_PATIENT_ID])
);

