CREATE TABLE [dbo].[CHEST_PAIN_PATIENT_STATUS] (
    [CHEST_PAIN_PATIENT_STATUS_ID] INT          IDENTITY (1, 1) NOT NULL,
    [NAME]                         VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_CHEST_PAIN_PATIENT_STATUS] PRIMARY KEY CLUSTERED ([CHEST_PAIN_PATIENT_STATUS_ID] ASC)
);

