CREATE TABLE [dbo].[CHEST_PAIN_ASPIRIN_GIVEN_BY] (
    [CHEST_PAIN_ASPIRIN_GIVEN_BY_ID] INT          IDENTITY (1, 1) NOT NULL,
    [NAME]                           VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_CHEST_PAIN_ASPIRIN_GIVEN_BY] PRIMARY KEY CLUSTERED ([CHEST_PAIN_ASPIRIN_GIVEN_BY_ID] ASC)
);

