CREATE TABLE [dbo].[CHEST_PAIN_DIAGNOSIS_OTHER] (
    [CHEST_PAIN_DIAGNOSIS_OTHER_ID] INT          IDENTITY (1, 1) NOT NULL,
    [NAME]                          VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_CHEST_PAIN_DIAGNOSIS_OTHER] PRIMARY KEY CLUSTERED ([CHEST_PAIN_DIAGNOSIS_OTHER_ID] ASC)
);

