CREATE TABLE [dbo].[CHEST_PAIN_FIRST_TYPE_CONTACT] (
    [CHEST_PAIN_FIRST_TYPE_CONTACT_ID] INT          IDENTITY (1, 1) NOT NULL,
    [NAME]                             VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_CHEST_PAIN_FIRST_TYPE_CONTACT] PRIMARY KEY CLUSTERED ([CHEST_PAIN_FIRST_TYPE_CONTACT_ID] ASC)
);

