CREATE TABLE [dbo].[CHEST_PAIN_DIAGNOSIS] (
    [CHEST_PAIN_DIAGNOSIS_ID] INT          IDENTITY (1, 1) NOT NULL,
    [DIAGNOSIS]               VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_CHEST_PAIN_DIAGNOSIS] PRIMARY KEY CLUSTERED ([CHEST_PAIN_DIAGNOSIS_ID] ASC)
);

