CREATE TABLE [dbo].[CHEST_PAIN_PATIENT_SYMPTOM] (
    [CHEST_PAIN_PATIENT_SYMPTOM_ID] INT      IDENTITY (1, 1) NOT NULL,
    [CHEST_PAIN_PATIENT_ID]         INT      NOT NULL,
    [CHEST_PAIN_MASTER_SYMPTOM_ID]  INT      NOT NULL,
    [CREATE_DATE]                   DATETIME CONSTRAINT [DF_CHEST_PAIN_PATIENT_SYMPTOM_CREATE_DATE] DEFAULT (getdate()) NOT NULL,
    [CREATED_BY_USER_ID]            INT      NOT NULL,
    [UPDATE_DATE]                   DATETIME NULL,
    [UPDATED_BY_USER_ID]            INT      NULL,
    CONSTRAINT [PK_CHEST_PAIN_PATIENT_SYMPTOM] PRIMARY KEY CLUSTERED ([CHEST_PAIN_PATIENT_SYMPTOM_ID] ASC),
    CONSTRAINT [FK_CHEST_PAIN_PATIENT_SYMPTOM_CHEST_PAIN_MASTER_SYMPTOM] FOREIGN KEY ([CHEST_PAIN_MASTER_SYMPTOM_ID]) REFERENCES [dbo].[CHEST_PAIN_MASTER_SYMPTOM] ([CHEST_PAIN_MASTER_SYMPTOM_ID]),
    CONSTRAINT [FK_CHEST_PAIN_PATIENT_SYMPTOM_CHEST_PAIN_PATIENT] FOREIGN KEY ([CHEST_PAIN_PATIENT_ID]) REFERENCES [dbo].[CHEST_PAIN_PATIENT] ([CHEST_PAIN_PATIENT_ID]),
    CONSTRAINT [FK_CHEST_PAIN_PATIENT_SYMPTOM_PdtsUser] FOREIGN KEY ([CREATED_BY_USER_ID]) REFERENCES [dbo].[PdtsUser] ([USER_ID]),
    CONSTRAINT [FK_CHEST_PAIN_PATIENT_SYMPTOM_PdtsUser1] FOREIGN KEY ([UPDATED_BY_USER_ID]) REFERENCES [dbo].[PdtsUser] ([USER_ID])
);

