CREATE TABLE [dbo].[CHEST_PAIN_FIBRI_GIVEN] (
    [CHEST_PAIN_FIBRI_GIVEN_ID] INT          IDENTITY (1, 1) NOT NULL,
    [NAME]                      VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_CHEST_PAIN_FIBRI_GIVEN] PRIMARY KEY CLUSTERED ([CHEST_PAIN_FIBRI_GIVEN_ID] ASC)
);

