CREATE TABLE [dbo].[CHEST_PAIN_MASTER_SYMPTOM] (
    [CHEST_PAIN_MASTER_SYMPTOM_ID] INT          IDENTITY (1, 1) NOT NULL,
    [NAME]                         VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_CHEST_PAIN_MASTER_SYMPTOM] PRIMARY KEY CLUSTERED ([CHEST_PAIN_MASTER_SYMPTOM_ID] ASC)
);

