CREATE TABLE [dbo].[CHEST_PAIN_ASPIRIN_RECEIVED] (
    [CHEST_PAIN_ASPIRIN_RECEIVED_ID] INT          IDENTITY (1, 1) NOT NULL,
    [NAME]                           VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_CHEST_PAIN_ASPIRIN_RECEIVED_BY] PRIMARY KEY CLUSTERED ([CHEST_PAIN_ASPIRIN_RECEIVED_ID] ASC)
);

