CREATE TABLE [dbo].[CHEST_PAIN_FACILITY_AGREE_TO_EMS_STEMI] (
    [CHEST_PAIN_FACILITY_AGREE_TO_EMS_STEMI_ID] INT          IDENTITY (1, 1) NOT NULL,
    [NAME]                                      VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_CHEST_PAIN_FACILITY_AGREE_TO_EMS_STEMI] PRIMARY KEY CLUSTERED ([CHEST_PAIN_FACILITY_AGREE_TO_EMS_STEMI_ID] ASC)
);

