CREATE TABLE [dbo].[ECG_PERFORMER] (
    [ECG_PERFORMER_TYPE_ID] INT          IDENTITY (1, 1) NOT NULL,
    [NAME]                  VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_ECG_PERFORMER] PRIMARY KEY CLUSTERED ([ECG_PERFORMER_TYPE_ID] ASC)
);

