CREATE TABLE [dbo].[ED_ACTION_PLAN_COMMENT] (
    [ED_ACTION_PLAN_COMMENT_ID] INT            IDENTITY (1, 1) NOT NULL,
    [ED_ACTION_PLAN_ID]         INT            NOT NULL,
    [COMMENT]                   VARCHAR (1000) NOT NULL,
    [CREATE_DATE]               DATETIME       CONSTRAINT [DF_ED_ACTION_PLAN_COMMENT_CREATE_DATE] DEFAULT (getdate()) NOT NULL,
    [CREATED_BY_USER_ID]        INT            NOT NULL,
    [UPDATE_DATE]               DATETIME       NULL,
    [UPDATED_BY_USER_ID]        INT            NULL,
    CONSTRAINT [PK_ED_ACTION_PLAN_COMMENT] PRIMARY KEY CLUSTERED ([ED_ACTION_PLAN_COMMENT_ID] ASC),
    CONSTRAINT [FK_ED_ACTION_PLAN_COMMENT_CreateUser] FOREIGN KEY ([CREATED_BY_USER_ID]) REFERENCES [dbo].[PdtsUser] ([USER_ID]),
    CONSTRAINT [FK_ED_ACTION_PLAN_COMMENT_ED_ACTION_PLAN] FOREIGN KEY ([ED_ACTION_PLAN_ID]) REFERENCES [dbo].[ED_ACTION_PLAN] ([ED_ACTION_PLAN_ID]),
    CONSTRAINT [FK_ED_ACTION_PLAN_COMMENT_UpdateUser] FOREIGN KEY ([UPDATED_BY_USER_ID]) REFERENCES [dbo].[PdtsUser] ([USER_ID])
);

