CREATE TABLE [dbo].[ED_ACTION_PLAN] (
    [ED_ACTION_PLAN_ID]           INT           IDENTITY (1, 1) NOT NULL,
    [COID]                        VARCHAR (5)   NOT NULL,
    [ED_ACTION_PLAN_CATEGORY_ID]  INT           NOT NULL,
    [ED_ACTION]                   VARCHAR (500) NOT NULL,
    [RESPONSIBILE_PERSON]         VARCHAR (50)  NULL,
    [GOAL_TARGET_COMPLETION_DATE] DATETIME      NULL,
    [BASELINE]                    VARCHAR (500) NULL,
    [GOAL_TARGET]                 VARCHAR (500) NULL,
    [CREATE_DATE]                 DATETIME      CONSTRAINT [DF_ED_ACTION_PLAN_CREATE_DATE] DEFAULT (getdate()) NOT NULL,
    [CREATED_BY_USER_ID]          INT           NOT NULL,
    [UPDATE_DATE]                 DATETIME      NULL,
    [UPDATED_BY_USER_ID]          INT           NULL,
    [ED_ACTION_PLAN_STATUS_ID]    INT           NOT NULL,
    [PRIORITY]                    INT           CONSTRAINT [DF_ED_ACTION_PLAN_PRIORITY] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_ED_ACTION_PLAN] PRIMARY KEY CLUSTERED ([ED_ACTION_PLAN_ID] ASC),
    CONSTRAINT [FK_ED_ACTION_PLAN_CreateUser] FOREIGN KEY ([CREATED_BY_USER_ID]) REFERENCES [dbo].[PdtsUser] ([USER_ID]),
    CONSTRAINT [FK_ED_ACTION_PLAN_ED_ACTION_PLAN_CATEGORY] FOREIGN KEY ([ED_ACTION_PLAN_CATEGORY_ID]) REFERENCES [dbo].[ED_ACTION_PLAN_CATEGORY] ([ED_ACTION_PLAN_CATEGORY_ID]),
    CONSTRAINT [FK_ED_ACTION_PLAN_ED_ACTION_PLAN_STATUS] FOREIGN KEY ([ED_ACTION_PLAN_STATUS_ID]) REFERENCES [dbo].[ED_ACTION_PLAN_STATUS] ([ED_ACTION_PLAN_STATUS_ID]),
    CONSTRAINT [FK_ED_ACTION_PLAN_Facility] FOREIGN KEY ([COID]) REFERENCES [dbo].[Facility] ([COID]),
    CONSTRAINT [FK_ED_ACTION_PLAN_UpdateUser] FOREIGN KEY ([UPDATED_BY_USER_ID]) REFERENCES [dbo].[PdtsUser] ([USER_ID])
);

