CREATE TABLE [dbo].[ED_ACTION_PLAN_CATEGORY] (
    [ED_ACTION_PLAN_CATEGORY_ID] INT           IDENTITY (1, 1) NOT NULL,
    [NAME]                       VARCHAR (100) NOT NULL,
    CONSTRAINT [PK_ED_ACTION_PLAN_CATEGORY] PRIMARY KEY CLUSTERED ([ED_ACTION_PLAN_CATEGORY_ID] ASC)
);

