CREATE TABLE [dbo].[ED_ACTION_PLAN_STATUS] (
    [ED_ACTION_PLAN_STATUS_ID] INT          IDENTITY (1, 1) NOT NULL,
    [NAME]                     VARCHAR (50) NOT NULL,
    [SORT_ORDER]               INT          CONSTRAINT [DF_ED_ACTION_PLAN_STATUS_SORT_ORDER] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_ED_ACTION_PLAN_STATUS] PRIMARY KEY CLUSTERED ([ED_ACTION_PLAN_STATUS_ID] ASC)
);

