CREATE TABLE [dbo].[ED_CASH_PAYMENTS] (
    [ED_CASH_PAYMENT_ID]   INT             IDENTITY (1, 1) NOT NULL,
    [COID]                 VARCHAR (5)     NOT NULL,
    [FROM_DATE]            DATETIME        NOT NULL,
    [TO_DATE]              DATETIME        NOT NULL,
    [SUM_OF_CASH_PAYMENTS] DECIMAL (18, 2) NOT NULL,
    CONSTRAINT [PK_ED_CASH_PAYMENTS] PRIMARY KEY CLUSTERED ([ED_CASH_PAYMENT_ID] ASC),
    CONSTRAINT [FK_ED_CASH_PAYMENTS_Facility] FOREIGN KEY ([COID]) REFERENCES [dbo].[Facility] ([COID])
);

