CREATE TABLE [dbo].[ED_DISCHARGE_STATUS] (
    [ED_DISCHARGE_STATUS_ID] INT          IDENTITY (1, 1) NOT NULL,
    [NAME]                   VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_ED_DISCHARGE_STATUS] PRIMARY KEY CLUSTERED ([ED_DISCHARGE_STATUS_ID] ASC)
);

