CREATE TABLE [dbo].[EDM_MANAGING_COMPANY] (
    [EDM_MANAGING_COMPANY_ID] INT          IDENTITY (1, 1) NOT NULL,
    [NAME]                    VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_EDM_MANAGING_COMPANY] PRIMARY KEY CLUSTERED ([EDM_MANAGING_COMPANY_ID] ASC)
);

