CREATE TABLE [dbo].[EMPLOYED_PROVIDER_APPROVAL_CHAIN] (
    [EMPLOYED_PROVIDER_APPROVAL_CHAIN_ID] INT      IDENTITY (1, 1) NOT NULL,
    [PENDING_PROVIDER_ID]                 INT      NOT NULL,
    [USER_ID]                             INT      NOT NULL,
    [ORDER_OF_APPROVAL]                   TINYINT  NOT NULL,
    [APPROVED]                            BIT      CONSTRAINT [DF_EMPLOYED_PROVIDER_APPROVAL_CHAIN_APPROVED] DEFAULT ((0)) NOT NULL,
    [APPROVED_DATE]                       DATETIME NULL,
    [REJECTED]                            BIT      CONSTRAINT [DF_EMPLOYED_PROVIDER_APPROVAL_CHAIN_REJECTED] DEFAULT ((0)) NOT NULL,
    [REJECTED_DATE]                       DATETIME NULL,
    [IS_FINAL_APPROVER]                   BIT      CONSTRAINT [DF_EMPLOYED_PROVIDER_APPROVAL_CHAIN_IS_FINAL_APPROVER] DEFAULT ((0)) NOT NULL,
    [NOTIFICATION_SENT]                   BIT      CONSTRAINT [DF_EMPLOYED_PROVIDER_APPROVAL_CHAIN_NOTIFICATION_SENT] DEFAULT ((0)) NOT NULL,
    [NOTIFICATION_SENT_DATE]              DATETIME NULL,
    CONSTRAINT [PK_EMPLOYED_PROVIDER_APPROVAL_CHAIN] PRIMARY KEY CLUSTERED ([EMPLOYED_PROVIDER_APPROVAL_CHAIN_ID] ASC),
    CONSTRAINT [FK_EMPLOYED_PROVIDER_APPROVAL_CHAIN_PdtsUser] FOREIGN KEY ([USER_ID]) REFERENCES [dbo].[PdtsUser] ([USER_ID]),
    CONSTRAINT [FK_EMPLOYED_PROVIDER_APPROVAL_CHAIN_PENDING_PROVIDER] FOREIGN KEY ([PENDING_PROVIDER_ID]) REFERENCES [dbo].[PENDING_PROVIDER] ([PENDING_PROVIDER_ID])
);

