CREATE TABLE [dbo].[EMPLOYED_PROVIDER_FIELD_TO_TRACK] (
    [EMPLOYED_PROVIDER_FIELD_TO_TRACK_ID] INT           IDENTITY (1, 1) NOT NULL,
    [TABLE_NAME]                          VARCHAR (128) NOT NULL,
    [FIELD_NAME]                          VARCHAR (128) NOT NULL,
    [FRIENDLY_NAME]                       VARCHAR (50)  NOT NULL,
    CONSTRAINT [PK_EMPLOYED_PROVIDER_FIELD_TO_TRACK] PRIMARY KEY CLUSTERED ([EMPLOYED_PROVIDER_FIELD_TO_TRACK_ID] ASC)
);

