CREATE TABLE [dbo].[EMPLOYED_PROVIDER_APPROVAL_CHAIN_MASTER] (
    [EMPLOYED_PROVIDER_APPROVAL_CHAIN_MASTER_ID] INT     IDENTITY (1, 1) NOT NULL,
    [ROOT_USER_ID]                               INT     NOT NULL,
    [APPROVAL_USER_ID]                           INT     NOT NULL,
    [ORDER_OF_APPROVAL]                          TINYINT NOT NULL,
    [DIVISION_ID]                                INT     NOT NULL,
    [IS_FINAL_APPROVER]                          BIT     CONSTRAINT [DF_EMPLOYED_PROVIDER_APPROVAL_CHAIN_MASTER_IS_FINAL_APPROVER] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_EMPLOYED_PROVIDER_APPROVAL_CHAIN_MASTER] PRIMARY KEY CLUSTERED ([EMPLOYED_PROVIDER_APPROVAL_CHAIN_MASTER_ID] ASC),
    CONSTRAINT [FK_EMPLOYED_PROVIDER_APPROVAL_CHAIN_MASTER_Division] FOREIGN KEY ([DIVISION_ID]) REFERENCES [dbo].[Division] ([DIVISION_ID]),
    CONSTRAINT [FK_EMPLOYED_PROVIDER_APPROVAL_CHAIN_MASTER_PdtsUser] FOREIGN KEY ([ROOT_USER_ID]) REFERENCES [dbo].[PdtsUser] ([USER_ID]),
    CONSTRAINT [FK_EMPLOYED_PROVIDER_APPROVAL_CHAIN_MASTER_PdtsUser1] FOREIGN KEY ([APPROVAL_USER_ID]) REFERENCES [dbo].[PdtsUser] ([USER_ID])
);

