CREATE TABLE [dbo].[EMPLOYED_PROVIDER_CHANGE_NOTIFICATION] (
    [EMPLOYED_PROVIDER_CHANGE_NOTIFICATION_ID] INT IDENTITY (1, 1) NOT NULL,
    [USER_ID]                                  INT NOT NULL,
    [SUPERVISOR_USER_ID]                       INT NOT NULL,
    CONSTRAINT [PK_EMPLOYED_PROVIDER_CHANGE_NOTIFICATION] PRIMARY KEY CLUSTERED ([EMPLOYED_PROVIDER_CHANGE_NOTIFICATION_ID] ASC),
    CONSTRAINT [FK_EMPLOYED_PROVIDER_CHANGE_NOTIFICATION_PdtsUser] FOREIGN KEY ([USER_ID]) REFERENCES [dbo].[PdtsUser] ([USER_ID]),
    CONSTRAINT [FK_EMPLOYED_PROVIDER_CHANGE_NOTIFICATION_PdtsUser1] FOREIGN KEY ([SUPERVISOR_USER_ID]) REFERENCES [dbo].[PdtsUser] ([USER_ID])
);

