CREATE TABLE [dbo].[ER_CORE_MEASURE] (
    [ER_CORE_MEASURE_ID] INT         IDENTITY (1, 1) NOT NULL,
    [COID]               VARCHAR (5) NOT NULL,
    [MONTH]              INT         NOT NULL,
    [YEAR]               INT         NOT NULL,
    [SCORE]              INT         NOT NULL,
    [POINTS]             INT         CONSTRAINT [DF_ER_CORE_MEASURE_POINTS] DEFAULT ((0)) NOT NULL,
    [IS_PRELIMINARY]     BIT         CONSTRAINT [DF_ER_CORE_MEASURE_IS_PRELIMINARY] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_ER_CORE_MEASURE] PRIMARY KEY CLUSTERED ([ER_CORE_MEASURE_ID] ASC),
    CONSTRAINT [FK_ER_CORE_MEASURE_Facility] FOREIGN KEY ([COID]) REFERENCES [dbo].[Facility] ([COID])
);

