CREATE TABLE [dbo].[ER_CORE_MEASURE_POSSIBLE_POINTS] (
    [ER_CORE_MEASURE_POSSIBLE_POINTS_ID] INT         IDENTITY (1, 1) NOT NULL,
    [COID]                               VARCHAR (5) NOT NULL,
    [YEAR]                               INT         NOT NULL,
    [POINTS]                             INT         NOT NULL,
    CONSTRAINT [PK_ER_CORE_MEASURE_POSSIBLE_POINTS] PRIMARY KEY CLUSTERED ([ER_CORE_MEASURE_POSSIBLE_POINTS_ID] ASC),
    CONSTRAINT [FK_ER_CORE_MEASURE_POSSIBLE_POINTS_Facility] FOREIGN KEY ([COID]) REFERENCES [dbo].[Facility] ([COID])
);

