CREATE TABLE [dbo].[ER_DAILY_STATS_GROUP] (
    [ER_DAILY_STATS_GROUP_ID] INT          IDENTITY (1, 1) NOT NULL,
    [NAME]                    VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_ER_DAILY_STATS_GROUP] PRIMARY KEY CLUSTERED ([ER_DAILY_STATS_GROUP_ID] ASC)
);

