CREATE TABLE [dbo].[ER_DAILY_STATS_DEFINITION_TARGET] (
    [ER_DAILY_STATS_DEFINITION_TARGET_ID] INT             IDENTITY (1, 1) NOT NULL,
    [NAME]                                VARCHAR (50)    NOT NULL,
    [ER_DAILY_STATS_DEFINITION_ID]        INT             NOT NULL,
    [COID]                                VARCHAR (5)     NOT NULL,
    [YEAR]                                INT             NOT NULL,
    [MONTH]                               INT             NOT NULL,
    [TARGET]                              DECIMAL (10, 2) CONSTRAINT [DF_ER_DAILY_STATS_DEFINITION_TARGET_TARGET] DEFAULT ((0)) NOT NULL,
    [CREATE_DATE]                         DATETIME        CONSTRAINT [DF_ER_DAILY_STATS_DEFINITION_TARGET_CREATE_DATE] DEFAULT (getdate()) NOT NULL,
    [CREATED_BY_USER_ID]                  INT             NOT NULL,
    [UPDATE_DATE]                         DATETIME        NULL,
    [UPDATED_BY_USER_ID]                  INT             NULL,
    [DIVISION_ROLLUP_SORT_ORDER]          INT             NULL,
    [TARGET_IS_PERCENTAGE]                BIT             CONSTRAINT [DF_ER_DAILY_STATS_DEFINITION_TARGET_TARGET_IS_PERCENTAGE] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_ER_DAILY_STATS_DEFINITION_TARGET] PRIMARY KEY CLUSTERED ([ER_DAILY_STATS_DEFINITION_TARGET_ID] ASC),
    CONSTRAINT [FK_ER_DAILY_STATS_DEFINITION_TARGET_CreateUser] FOREIGN KEY ([CREATED_BY_USER_ID]) REFERENCES [dbo].[PdtsUser] ([USER_ID]),
    CONSTRAINT [FK_ER_DAILY_STATS_DEFINITION_TARGET_ER_DAILY_STATS_DEFINITION] FOREIGN KEY ([ER_DAILY_STATS_DEFINITION_ID]) REFERENCES [dbo].[ER_DAILY_STATS_DEFINITION] ([ER_DAILY_STATS_DEFINITION_ID]),
    CONSTRAINT [FK_ER_DAILY_STATS_DEFINITION_TARGET_Facility] FOREIGN KEY ([COID]) REFERENCES [dbo].[Facility] ([COID]),
    CONSTRAINT [FK_ER_DAILY_STATS_DEFINITION_TARGET_UpdateUser] FOREIGN KEY ([UPDATED_BY_USER_ID]) REFERENCES [dbo].[PdtsUser] ([USER_ID]),
    CONSTRAINT [UQ__ER_DAILY_STATS_D__1C09AFAD] UNIQUE NONCLUSTERED ([COID] ASC, [ER_DAILY_STATS_DEFINITION_ID] ASC, [YEAR] ASC, [MONTH] ASC)
);

