CREATE TABLE [dbo].[ER_DAILY_STATS_POSSIBLE_POINTS] (
    [ER_DAILY_STATS_POSSIBLE_POINTS] INT         IDENTITY (1, 1) NOT NULL,
    [COID]                           VARCHAR (5) NOT NULL,
    [ER_DAILY_STATS_DEFINITION_ID]   INT         NOT NULL,
    [YEAR]                           INT         NOT NULL,
    [POINTS]                         INT         NOT NULL,
    CONSTRAINT [PK_ER_DAILY_STATS_POSSIBLE_POINTS] PRIMARY KEY CLUSTERED ([ER_DAILY_STATS_POSSIBLE_POINTS] ASC),
    CONSTRAINT [FK_ER_DAILY_STATS_POSSIBLE_POINTS_ER_DAILY_STATS_DEFINITION] FOREIGN KEY ([ER_DAILY_STATS_DEFINITION_ID]) REFERENCES [dbo].[ER_DAILY_STATS_DEFINITION] ([ER_DAILY_STATS_DEFINITION_ID]),
    CONSTRAINT [FK_ER_DAILY_STATS_POSSIBLE_POINTS_Facility] FOREIGN KEY ([COID]) REFERENCES [dbo].[Facility] ([COID])
);

