CREATE TABLE [dbo].[ER_MONTHLY_DATA_DETAIL] (
    [ER_MONTHLY_DATA_DETAIL_ID] INT             IDENTITY (1, 1) NOT NULL,
    [ER_DATA_ID]                INT             NOT NULL,
    [CHARGE_CPT_CODE]           VARCHAR (5)     NOT NULL,
    [CHARGE_REV_CODE]           INT             NOT NULL,
    [SUM_OF_TOTAL_CASH_PYMT]    DECIMAL (18, 2) NOT NULL,
    [SUM_OF_CHRG_AMT]           DECIMAL (18, 2) NOT NULL,
    [SUM_OF_CHRG_FACTORS]       INT             NOT NULL,
    [CHARGE_HCPCS_PROC]         VARCHAR (6)     NULL,
    CONSTRAINT [PK_ER_MONTHLY_DATA_DETAIL] PRIMARY KEY CLUSTERED ([ER_MONTHLY_DATA_DETAIL_ID] ASC),
    CONSTRAINT [FK_ER_MONTHLY_DATA_DETAIL_ER_MONTHLY_DATA] FOREIGN KEY ([ER_DATA_ID]) REFERENCES [dbo].[ER_MONTHLY_DATA] ([ER_DATA_ID]) ON DELETE CASCADE
);

