CREATE TABLE [dbo].[ER_TOP_BOX_SCORE_POSSIBLE_POINTS] (
    [ER_TOP_BOX_SCORE_POSSIBLE_POINTS_ID] INT         IDENTITY (1, 1) NOT NULL,
    [COID]                                VARCHAR (5) NOT NULL,
    [QUESTION_ID]                         INT         NOT NULL,
    [YEAR]                                INT         NOT NULL,
    [POINTS]                              INT         NOT NULL,
    CONSTRAINT [PK_ER_TOP_BOX_SCORE_POSSIBLE_POINTS] PRIMARY KEY CLUSTERED ([ER_TOP_BOX_SCORE_POSSIBLE_POINTS_ID] ASC),
    CONSTRAINT [FK_ER_TOP_BOX_SCORE_POSSIBLE_POINTS_Facility] FOREIGN KEY ([COID]) REFERENCES [dbo].[Facility] ([COID]),
    CONSTRAINT [FK_ER_TOP_BOX_SCORE_POSSIBLE_POINTS_SURVEY_QUESTION] FOREIGN KEY ([QUESTION_ID]) REFERENCES [dbo].[SURVEY_QUESTION] ([QUESTION_ID])
);

