CREATE TABLE [dbo].[ER_TOP_BOX_SCORE] (
    [ED_TOP_BOX_SCORE_ID] INT            IDENTITY (1, 1) NOT NULL,
    [COID]                VARCHAR (5)    NOT NULL,
    [QUESTION_ID]         INT            NOT NULL,
    [QUARTER]             TINYINT        NOT NULL,
    [YEAR]                INT            NOT NULL,
    [TOP_BOX_SCORE]       DECIMAL (5, 2) NOT NULL,
    [POINTS]              INT            CONSTRAINT [DF_ER_TOP_BOX_SCORE_POINTS] DEFAULT ((0)) NOT NULL,
    [PRELIMINARY]         BIT            CONSTRAINT [DF_ER_TOP_BOX_SCORE_PRELIMINARY] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_ER_TOP_BOX_SCORE] PRIMARY KEY CLUSTERED ([ED_TOP_BOX_SCORE_ID] ASC),
    CONSTRAINT [FK_ER_TOP_BOX_SCORE_Facility] FOREIGN KEY ([COID]) REFERENCES [dbo].[Facility] ([COID]),
    CONSTRAINT [FK_ER_TOP_BOX_SCORE_SURVEY_QUESTION] FOREIGN KEY ([QUESTION_ID]) REFERENCES [dbo].[SURVEY_QUESTION] ([QUESTION_ID])
);

