CREATE TABLE [dbo].[FACILITY_QUARTERLY_CERTIFICATION] (
    [FACILITY_QUARTERLY_CERTIFICATION_ID] INT          IDENTITY (1, 1) NOT NULL,
    [COID]                                VARCHAR (5)  NOT NULL,
    [QUARTER]                             TINYINT      NOT NULL,
    [YEAR]                                INT          NOT NULL,
    [CEO_CERTIFIED]                       BIT          CONSTRAINT [DF_FACILITY_QUARTERLY_CERTIFICATION_CEO_CERTIFIED] DEFAULT ((0)) NOT NULL,
    [CEO]                                 VARCHAR (50) NULL,
    [CEO_CERT_DATE]                       DATETIME     NULL,
    [CFO_CERTIFIED]                       BIT          CONSTRAINT [DF_FACILITY_QUARTERLY_CERTIFICATION_CFO_CERTIFIED] DEFAULT ((0)) NOT NULL,
    [CFO]                                 VARCHAR (50) NULL,
    [CFO_CERT_DATE]                       DATETIME     NULL,
    [CONTROLLER_CERTIFIED]                BIT          CONSTRAINT [DF_FACILITY_QUARTERLY_CERTIFICATION_CONTROLLER_CERTIFIED] DEFAULT ((0)) NOT NULL,
    [CONTROLLER]                          VARCHAR (50) NULL,
    [CONTROLLER_CERT_DATE]                DATETIME     NULL,
    [PRE]                                 BIT          CONSTRAINT [DF_FACILITY_QUARTERLY_CERTIFICATION_PRE] DEFAULT ((0)) NOT NULL,
    [POST]                                BIT          CONSTRAINT [DF_FACILITY_QUARTERLY_CERTIFICATION_POST] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_FACILITY_QUARTERLY_CERTIFICATION] PRIMARY KEY CLUSTERED ([FACILITY_QUARTERLY_CERTIFICATION_ID] ASC),
    CONSTRAINT [FK_FACILITY_QUARTERLY_CERTIFICATION_Facility] FOREIGN KEY ([COID]) REFERENCES [dbo].[Facility] ([COID])
);

