CREATE TABLE [dbo].[GENDER] (
    [GENDER_ID]  INT         IDENTITY (1, 1) NOT NULL,
    [SHORT_NAME] VARCHAR (1) NOT NULL,
    [LONG_NAME]  VARCHAR (6) NOT NULL,
    CONSTRAINT [PK_GENDER] PRIMARY KEY CLUSTERED ([GENDER_ID] ASC)
);

