CREATE TABLE [dbo].[GL_DEPARTMENT] (
    [GL_DEPARTMENT_ID] INT           IDENTITY (1, 1) NOT NULL,
    [GL_DEPT]          VARCHAR (5)   NOT NULL,
    [NAME]             VARCHAR (100) NOT NULL,
    CONSTRAINT [PK_GL_DEPARTMENT] PRIMARY KEY CLUSTERED ([GL_DEPARTMENT_ID] ASC)
);

