CREATE TABLE [dbo].[GL_SUB_ACCOUNT] (
    [GL_SUB_ACCOUNT_ID] INT           IDENTITY (1, 1) NOT NULL,
    [SUB_ACCOUNT]       VARCHAR (5)   NOT NULL,
    [NAME]              VARCHAR (100) NOT NULL,
    [FS_CATEGORY]       VARCHAR (10)  NOT NULL,
    [FS_CATEGORY_NAME]  VARCHAR (100) NOT NULL,
    CONSTRAINT [PK_GL_SUB_ACCOUNT] PRIMARY KEY CLUSTERED ([GL_SUB_ACCOUNT_ID] ASC)
);

