CREATE TABLE [dbo].[GMENAC_RATIO] (
    [GMENAC_RATIO_ID]        INT            IDENTITY (1, 1) NOT NULL,
    [SPECIALTY_GROUP_ID]     INT            NOT NULL,
    [SPECIALTY_ID]           INT            NOT NULL,
    [DEMAN_PER_ONE_THOUSAND] DECIMAL (5, 2) CONSTRAINT [DF_GMENAC_RATIO_DEMAN_PER_ONE_THOUSAND] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_GMENAC_RATIO] PRIMARY KEY CLUSTERED ([GMENAC_RATIO_ID] ASC),
    CONSTRAINT [FK_GMENAC_RATIO_Specialty] FOREIGN KEY ([SPECIALTY_ID]) REFERENCES [dbo].[Specialty] ([SPECIALTY_ID]),
    CONSTRAINT [FK_GMENAC_RATIO_SpecialtyGroup] FOREIGN KEY ([SPECIALTY_GROUP_ID]) REFERENCES [dbo].[SpecialtyGroup] ([SPECIALTY_GROUP_ID])
);

