CREATE TABLE [dbo].[Holiday] (
    [HOLIDAY_ID]    INT      IDENTITY (1, 1) NOT NULL,
    [HOLIDAY_DATE]  DATETIME NOT NULL,
    [HOLIDAY_YEAR]  SMALLINT NOT NULL,
    [HOLIDAY_MONTH] TINYINT  NOT NULL,
    [HOLIDAY_DAY]   TINYINT  NOT NULL,
    CONSTRAINT [PK_Holiday] PRIMARY KEY CLUSTERED ([HOLIDAY_ID] ASC)
);

