CREATE TABLE [dbo].[ig_BillingSystems] (
    [BILLINGSYSTEM_ID]   INT          IDENTITY (1, 1) NOT NULL,
    [BILLINGSYSTEM_DESC] VARCHAR (50) NULL,
    CONSTRAINT [PK_igBillingSystems] PRIMARY KEY CLUSTERED ([BILLINGSYSTEM_ID] ASC)
);

