CREATE TABLE [dbo].[ig_CorpAudit] (
    [CAUDIT_ID]        INT           IDENTITY (1, 1) NOT NULL,
    [CAUDIT_SCHEDULED] VARCHAR (1)   NULL,
    [CAUDIT_STATUS_ID] INT           NULL,
    [CAUDIT_AUDITOR]   VARCHAR (100) NULL,
    [CAUDIT_NOTES]     VARCHAR (MAX) NULL,
    CONSTRAINT [PK_igCorpAudit] PRIMARY KEY CLUSTERED ([CAUDIT_ID] ASC),
    CONSTRAINT [FK_IGCORPAUDIT_IGCORPAUDITSTS] FOREIGN KEY ([CAUDIT_STATUS_ID]) REFERENCES [dbo].[ig_CorpAuditStatus] ([CASTATUS_ID])
);

