CREATE TABLE [dbo].[ig_MGMABenchmark] (
    [MGMABM_ID]     INT             IDENTITY (1, 1) NOT NULL,
    [SPECIALTY_ID]  INT             NULL,
    [COLLECTIONS]   DECIMAL (11, 2) NULL,
    [GROSS_CHARGES] DECIMAL (11, 2) NULL,
    [BM_PERCENT]    DECIMAL (11, 2) NULL,
    CONSTRAINT [PK_igMGMABenchmark] PRIMARY KEY CLUSTERED ([MGMABM_ID] ASC),
    CONSTRAINT [FK_IGMGMABENCHMARK_SPECIALTY] FOREIGN KEY ([SPECIALTY_ID]) REFERENCES [dbo].[Specialty] ([SPECIALTY_ID])
);

