CREATE TABLE [dbo].[ig_PracticeType] (
    [PRACTICETYPE_ID]   INT          IDENTITY (1, 1) NOT NULL,
    [PRACTICETYPE_DESC] VARCHAR (50) NULL,
    CONSTRAINT [PK_igPracticeType] PRIMARY KEY CLUSTERED ([PRACTICETYPE_ID] ASC)
);

