CREATE TABLE [dbo].[ig_RiskStatus] (
    [IGRISKSTATUS_ID]    INT           IDENTITY (1, 1) NOT NULL,
    [IGRISKSTATUS_DESC]  VARCHAR (50)  NULL,
    [IGRISKSTATUS_COLOR] VARCHAR (10)  NULL,
    [RISK_DEFINITION]    VARCHAR (500) NULL,
    CONSTRAINT [PK_igRiskStatus] PRIMARY KEY CLUSTERED ([IGRISKSTATUS_ID] ASC)
);

