CREATE TABLE [dbo].[ig_Status] (
    [IGSTATUS_ID]   INT          IDENTITY (1, 1) NOT NULL,
    [IGSTATUS_DESC] VARCHAR (50) NULL,
    CONSTRAINT [PK_igStatus] PRIMARY KEY CLUSTERED ([IGSTATUS_ID] ASC)
);

