CREATE TABLE [dbo].[ig_Worksheet_Notes] (
    [WS_NOTE_ID]      INT           IDENTITY (1, 1) NOT NULL,
    [WORKSHEET_ID]    INT           NOT NULL,
    [WS_NOTE_TYPE_ID] INT           NOT NULL,
    [CREATED_DATE]    DATETIME      CONSTRAINT [DF_ig_Worksheet_Notes_CREATED_DATE] DEFAULT (getdate()) NOT NULL,
    [CREATED_BY]      INT           NOT NULL,
    [WS_NOTE_TEXT]    VARCHAR (MAX) NOT NULL,
    [UPDATED_DATE]    DATETIME      NULL,
    [UPDATED_BY]      INT           NULL,
    CONSTRAINT [PK_igWorksheetNotes] PRIMARY KEY CLUSTERED ([WS_NOTE_ID] ASC),
    CONSTRAINT [FK_IGWKSHEET_IGWKSHEETNOTES] FOREIGN KEY ([WORKSHEET_ID]) REFERENCES [dbo].[ig_Worksheets] ([WORKSHEET_ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_IGWKSHEETNOTES_IGWKSHEETNOTETYPES] FOREIGN KEY ([WS_NOTE_TYPE_ID]) REFERENCES [dbo].[ig_Worksheet_NoteTypes] ([WS_NOTE_TYPE_ID]),
    CONSTRAINT [FK_IGWORKSHEETNOTES_CREATEUSER] FOREIGN KEY ([CREATED_BY]) REFERENCES [dbo].[PdtsUser] ([USER_ID]),
    CONSTRAINT [FK_IGWORKSHEETNOTES_UPDATEUSER] FOREIGN KEY ([UPDATED_BY]) REFERENCES [dbo].[PdtsUser] ([USER_ID])
);

