CREATE TABLE [dbo].[ig_Worksheet_History] (
    [WORKSHEET_HISTORY_ID]              INT             IDENTITY (1, 1) NOT NULL,
    [WORKSHEET_ID]                      INT             NOT NULL,
    [COID]                              VARCHAR (5)     NULL,
    [PROVIDER_ID]                       INT             NULL,
    [IGTYPE_ID]                         INT             NULL,
    [IGSTATUS_ID]                       INT             NULL,
    [IG_PRACTICETYPE_ID]                INT             NULL,
    [IG_BILLINGSYSTEM_ID]               INT             NULL,
    [IG_MGMACOMPTYPE_ID]                INT             NULL,
    [GROUP_EMP_AGREEMENT_FLAG]          VARCHAR (1)     NULL,
    [PHYSICIAN_SALARY]                  DECIMAL (11, 2) NOT NULL,
    [START_DATE]                        DATETIME        NULL,
    [MONTHLY_AMT]                       DECIMAL (11, 2) NOT NULL,
    [MONTHS]                            INT             NOT NULL,
    [TOTAL_AMT]                         DECIMAL (11, 2) NOT NULL,
    [FASB_LOSS_AMT]                     DECIMAL (11, 2) NOT NULL,
    [FASB_START_EXP]                    DECIMAL (11, 2) NOT NULL,
    [ADV_PAYMENT_AMT]                   DECIMAL (11, 2) NOT NULL,
    [ADV_RECOVERY_MONTHS]               INT             NOT NULL,
    [IG_COMPLETION_DATE]                DATETIME        NULL,
    [AMT_MARKETING_EXP]                 DECIMAL (11, 2) NOT NULL,
    [AMT_RELOCATION_EXP]                DECIMAL (11, 2) NOT NULL,
    [AMT_EDUCATION_STIPEND]             DECIMAL (11, 2) NOT NULL,
    [AMT_STUDENT_LOANS]                 DECIMAL (11, 2) NOT NULL,
    [AMT_CONSULTING_COSTS]              DECIMAL (11, 2) NOT NULL,
    [AMT_SIGNON_BONUS]                  DECIMAL (11, 2) NOT NULL,
    [AMT_STARTUP_MISC]                  DECIMAL (11, 2) NOT NULL,
    [PM_CONSULTANT_FNAME]               VARCHAR (50)    NULL,
    [PM_CONSULTANT_LNAME]               VARCHAR (50)    NULL,
    [PM_CONSULTANT_EMAIL]               VARCHAR (100)   NULL,
    [PM_CONSULTANT_PHONE]               VARCHAR (25)    NULL,
    [PM_CONSULTANT_NOTES]               VARCHAR (MAX)   NULL,
    [CRED_CONSULTANT_FNAME]             VARCHAR (50)    NULL,
    [CRED_CONSULTANT_LNAME]             VARCHAR (50)    NULL,
    [CRED_CONSULTANT_EMAIL]             VARCHAR (100)   NULL,
    [CRED_CONSULTANT_PHONE]             VARCHAR (25)    NULL,
    [CRED_CONSULTANT_NOTES]             VARCHAR (MAX)   NULL,
    [PROVIDER_SENTDATE_MEDICARE]        DATETIME        NULL,
    [PROVIDER_SENTDATE_MEDICAID]        DATETIME        NULL,
    [PROVIDER_SENTDATE_BCBS]            DATETIME        NULL,
    [PROVIDER_APPROVED_MEDICARE]        DATETIME        NULL,
    [PROVIDER_APPROVED_MEDICAID]        DATETIME        NULL,
    [PROVIDER_APPROVED_BCBS]            DATETIME        NULL,
    [PROVIDER_EFFECTIVE_MEDICARE]       DATETIME        NULL,
    [PROVIDER_EFFECTIVE_MEDICAID]       DATETIME        NULL,
    [PROVIDER_EFFECTIVE_BCBS]           DATETIME        NULL,
    [CREATED_DATE]                      DATETIME        NULL,
    [CREATED_BY]                        INT             NULL,
    [ADVPD_HOSTFASB_BALANCE]            DECIMAL (11, 2) NOT NULL,
    [ADVPD_CHECK_DATE]                  DATETIME        NULL,
    [ADVPD_CHECK_NUMBER]                INT             NULL,
    [ADVPD_CEO_CFO_INITIALS]            VARCHAR (50)    NULL,
    [ADVPD_AR_0_30]                     DECIMAL (11, 2) NOT NULL,
    [ADVPD_AR_31_60]                    DECIMAL (11, 2) NOT NULL,
    [ADVPD_AR_61_90]                    DECIMAL (11, 2) NOT NULL,
    [ADVPD_AR_91_120]                   DECIMAL (11, 2) NOT NULL,
    [ADVPD_AR_121_150]                  DECIMAL (11, 2) NOT NULL,
    [ADVPD_AR_150_PLUS]                 DECIMAL (11, 2) NOT NULL,
    [ADVPD_AMT_MARKETING_EXP]           DECIMAL (11, 2) NOT NULL,
    [ADVPD_AMT_RELOCATION_EXP]          DECIMAL (11, 2) NOT NULL,
    [ADVPD_AMT_EDUCATION_STIPEND]       DECIMAL (11, 2) NOT NULL,
    [ADVPD_AMT_STUDENT_LOANS]           DECIMAL (11, 2) NOT NULL,
    [ADVPD_AMT_CONSULTING_COSTS]        DECIMAL (11, 2) NOT NULL,
    [ADVPD_AMT_SIGNON_BONUS]            DECIMAL (11, 2) NOT NULL,
    [ADVPD_AMT_STARTUP_MISC]            DECIMAL (11, 2) NOT NULL,
    [RECRUITING_MONTHS]                 INT             NULL,
    [LASTDAY_OF_FIRSTMONTH]             INT             NULL,
    [FIRSTDAY_STARTFLAG]                VARCHAR (1)     NULL,
    [EXCESS_PAYMENT_ROLL_FLAG]          VARCHAR (1)     NULL,
    [UPDATED_DATE]                      DATETIME        NULL,
    [UPDATED_BY]                        INT             NULL,
    [ADVPD_AR_TOTAL]                    DECIMAL (11, 2) NOT NULL,
    [ADVPD_EXPENSE_TOTAL]               DECIMAL (11, 2) NOT NULL,
    [IG_Modification_Locked]            VARCHAR (1)     NULL,
    [AR_RiskStatus_Current]             INT             NULL,
    [Volume_RiskStatus_Current]         INT             NULL,
    [Collection_RiskStatus_Current]     INT             NULL,
    [AR_RiskStatus_Proposed]            INT             NULL,
    [Volume_RiskStatus_Proposed]        INT             NULL,
    [Collection_RiskStatus_Proposed]    INT             NULL,
    [AR_RiskStatus_Override]            INT             NULL,
    [Volume_RiskStatus_Override]        INT             NULL,
    [Collection_RiskStatus_Override]    INT             NULL,
    [PROVIDER_SENTDATE_MEDICARE_GROUP]  DATETIME        NULL,
    [PROVIDER_APPROVED_MEDICARE_GROUP]  DATETIME        NULL,
    [PROVIDER_EFFECTIVE_MEDICARE_GROUP] DATETIME        NULL,
    [PROVIDER_SENTDATE_MEDICAID_GROUP]  DATETIME        NULL,
    [PROVIDER_APPROVED_MEDICAID_GROUP]  DATETIME        NULL,
    [PROVIDER_EFFECTIVE_MEDICAID_GROUP] DATETIME        NULL,
    [PROVIDER_SENTDATE_CAQH]            DATETIME        NULL,
    [PROVIDER_APPROVED_CAQH]            DATETIME        NULL,
    [PROVIDER_EFFECTIVE_CAQH]           DATETIME        NULL,
    [ADVPD_STARTDATE]                   DATETIME        NULL,
    [ADV_AMORTIZATION_AMT]              DECIMAL (11, 2) NOT NULL,
    [TOTAL_FASB_AMT]                    DECIMAL (11, 2) NOT NULL,
    [FIRST_MONTH_AMT]                   DECIMAL (11, 2) NOT NULL,
    [LAST_MONTH_AMT]                    DECIMAL (11, 2) NOT NULL,
    [ADVPD_FASB_VARIANCE]               DECIMAL (11, 4) NOT NULL,
    [ADVPD_AMORTIZATION_AMT]            DECIMAL (11, 2) NOT NULL,
    [ADVPD_NET_CHK_AMT_DUE_TO_PHYS]     DECIMAL (11, 2) NOT NULL,
    [ADVPD_NET_CHK_AMT_PAID_TO_PHYS]    DECIMAL (11, 2) NOT NULL,
    [ADVPD_REMAINING_FASB_BAL]          DECIMAL (11, 2) NOT NULL,
    [LTD_Payments]                      DECIMAL (11, 2) NOT NULL,
    [AR_RiskStatus_Prior]               INT             NULL,
    [Volume_RiskStatus_Prior]           INT             NULL,
    [Collection_RiskStatus_Prior]       INT             NULL,
    [AlertStatus_Current]               INT             NULL,
    [AlertStatus_Prior]                 INT             NULL,
    [last_monthlyfinancial_date]        INT             NULL,
    [MonthEndStatus]                    VARCHAR (15)    NULL,
    [PM_CONSULTANT_PHONE2]              VARCHAR (25)    NULL,
    [PM_COMPANY]                        VARCHAR (100)   NULL,
    [CredCompletedDate]                 DATETIME        NULL,
    [CredCompletedFlag]                 VARCHAR (1)     NULL,
    [RECORD_START_DATE]                 DATETIME        NOT NULL,
    [RECORD_END_DATE]                   DATETIME        NULL,
    [EXTENSION_1]                       SMALLINT        NULL,
    [EXTENSION_2]                       SMALLINT        NULL,
    [IG_BONUS]                          DECIMAL (11, 2) NULL,
    [INS_POLICY_PREMIUM_ALLOWANCE]      DECIMAL (11, 2) NULL,
    [IMPUTED_INTEREST_RATE]             DECIMAL (5, 2)  NULL,
    [IMMIGRATION_FEES]                  DECIMAL (11, 2) NULL,
    [FORGIVENESS_PERIOD]                INT             NULL,
    [FORGIVENESS_INTEREST_RATE]         DECIMAL (5, 2)  NULL,
    CONSTRAINT [PK_igWorksheetHistory] PRIMARY KEY CLUSTERED ([WORKSHEET_HISTORY_ID] ASC)
);

