CREATE TABLE [dbo].[INITIAL_PCI_OUTCOME] (
    [INITIAL_PCI_OUTCOME_ID] INT          IDENTITY (1, 1) NOT NULL,
    [NAME]                   VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_INITIAL_PCI_OUTCOME] PRIMARY KEY CLUSTERED ([INITIAL_PCI_OUTCOME_ID] ASC)
);

