CREATE TABLE [dbo].[MASTER_ED_TIER_RANKING] (
    [ED_TIER_RANKING_ID] INT           IDENTITY (1, 1) NOT NULL,
    [NAME]               NVARCHAR (50) NOT NULL,
    CONSTRAINT [PK_MASTER_ED_TIER_RANKING] PRIMARY KEY CLUSTERED ([ED_TIER_RANKING_ID] ASC)
);

