CREATE TABLE [dbo].[MASTER_QUARTERLY_CERTIFICATION] (
    [MASTER_QUARTERLY_CERTIFICATION_ID] INT            IDENTITY (1, 1) NOT NULL,
    [CERTIFICATION_LANGUAGE]            VARCHAR (1000) NOT NULL,
    [PRE]                               BIT            CONSTRAINT [DF_MASTER_QUARTERLY_CERTIFICATION_PRE] DEFAULT ((0)) NOT NULL,
    [POST]                              BIT            CONSTRAINT [DF_MASTER_QUARTERLY_CERTIFICATION_POST] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_MASTER_QUARTERLY_CERTIFICATION] PRIMARY KEY CLUSTERED ([MASTER_QUARTERLY_CERTIFICATION_ID] ASC)
);

