CREATE TABLE [dbo].[MASTER_ER_LEVEL] (
    [ER_LEVEL_ID]   INT          IDENTITY (1, 1) NOT NULL,
    [CPT_CODE]      VARCHAR (5)  NOT NULL,
    [ER_LEVEL_DESC] VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_MASTER_ER_LEVEL] PRIMARY KEY CLUSTERED ([ER_LEVEL_ID] ASC)
);

