CREATE TABLE [dbo].[MASTER_FINANCIAL_CLASS] (
    [FINANCIAL_CLASS_ID]   INT          IDENTITY (1, 1) NOT NULL,
    [FINANCIAL_CLASS]      INT          NOT NULL,
    [FINANCIAL_CLASS_DESC] VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_MASTER_FINANCIAL_CLASS] PRIMARY KEY CLUSTERED ([FINANCIAL_CLASS_ID] ASC)
);

