CREATE TABLE [dbo].[OP_IMAGING_MEASURE] (
    [OP_IMAGING_MEASURE_ID] INT           IDENTITY (1, 1) NOT NULL,
    [NAME]                  VARCHAR (50)  NOT NULL,
    [OPERAND1]              VARCHAR (128) NOT NULL,
    [OPERAND2]              VARCHAR (128) NOT NULL,
    [MIN_VALUE]             INT           NOT NULL,
    [MAX_VALUE]             INT           NOT NULL,
    [SORT_ORDER]            INT           CONSTRAINT [DF_OP_IMAGING_MEASURE_SORT_ORDER] DEFAULT ((0)) NOT NULL,
    [EXECUTIVE_SUMMARY]     BIT           CONSTRAINT [DF_OP_IMAGING_MEASURE_EXECUTIVE_SUMMARY] DEFAULT ((0)) NOT NULL,
    [MAX_THRESHOLD]         INT           CONSTRAINT [DF_OP_IMAGING_MEASURE_MAX_THRESHOLD] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_OP_IMAGING_MEASURE] PRIMARY KEY CLUSTERED ([OP_IMAGING_MEASURE_ID] ASC)
);

