CREATE TABLE [dbo].[OP_IMAGING_FOLLOWUP_UNABLE_REASON] (
    [OP_IMAGING_FOLLOWUP_UNABLE_REASON_ID] INT          IDENTITY (1, 1) NOT NULL,
    [REASON]                               VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_OP_IMAGING_UNABLE_REASON] PRIMARY KEY CLUSTERED ([OP_IMAGING_FOLLOWUP_UNABLE_REASON_ID] ASC)
);

