CREATE TABLE [dbo].[OP_IMAGING_DASHBOARD_CROSSWALK] (
    [OP_IMAGING_DASHBOARD_CROSSWALK_ID]       INT           IDENTITY (1, 1) NOT NULL,
    [LIFEPOINT_HOSPITAL_MANAGEMENT_SYSTEM_ID] INT           NOT NULL,
    [SOURCE_FIELD_NAME]                       VARCHAR (50)  NOT NULL,
    [TARGET_FIELD_NAME]                       VARCHAR (50)  NOT NULL,
    [LOOKUP_TABLE]                            VARCHAR (128) NULL,
    [LOOKUP_TABLE_SOURCE_COLUMN]              VARCHAR (128) NULL,
    CONSTRAINT [PK_OP_IMAGING_DASHBOARD_CROSSWALK] PRIMARY KEY CLUSTERED ([OP_IMAGING_DASHBOARD_CROSSWALK_ID] ASC),
    CONSTRAINT [FK_OP_IMAGING_DASHBOARD_CROSSWALK_LIFEPOINT_HOSPITAL_MANAGEMENT_SYSTEM] FOREIGN KEY ([LIFEPOINT_HOSPITAL_MANAGEMENT_SYSTEM_ID]) REFERENCES [dbo].[LIFEPOINT_HOSPITAL_MANAGEMENT_SYSTEM] ([LIFEPOINT_HOSPITAL_MANAGEMENT_SYSTEM_ID])
);

