CREATE TABLE [dbo].[OP_ORDER_TYPE] (
    [OP_ORDER_TYPE_ID] INT          IDENTITY (1, 1) NOT NULL,
    [NAME]             VARCHAR (50) NOT NULL,
    [SORT_ORDER]       INT          CONSTRAINT [DF_OP_ORDER_TYPE_SORT_ORDER] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_OP_ORDER_TYPE] PRIMARY KEY CLUSTERED ([OP_ORDER_TYPE_ID] ASC)
);

