CREATE TABLE [dbo].[PARALLON_SERVICE_GL_ACCOUNT] (
    [PARALLON_SERVICE_GL_ACCOUNT_ID] INT         IDENTITY (1, 1) NOT NULL,
    [PARALLON_SERVICE_ID]            INT         NOT NULL,
    [COID]                           VARCHAR (5) NULL,
    [ACCOUNT]                        INT         NOT NULL,
    [CREATE_DATE]                    DATETIME    CONSTRAINT [DF_PARALLON_SERVICE_GL_ACCOUNT_CREATE_DATE] DEFAULT (getdate()) NOT NULL,
    [CREATED_BY_USER_ID]             INT         NOT NULL,
    [UPDATE_DATE]                    DATETIME    NULL,
    [UPDATED_BY_USER_ID]             INT         NULL,
    [ACTIVE]                         BIT         CONSTRAINT [DF_PARALLON_SERVICE_GL_ACCOUNT_ACTIVE] DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_PARALLON_SERVICE_GL_ACCOUNT] PRIMARY KEY CLUSTERED ([PARALLON_SERVICE_GL_ACCOUNT_ID] ASC),
    CONSTRAINT [FK_PARALLON_SERVICE_GL_ACCOUNT_PARALLON_SERVICE] FOREIGN KEY ([PARALLON_SERVICE_ID]) REFERENCES [dbo].[PARALLON_SERVICE] ([PARALLON_SERVICE_ID]),
    CONSTRAINT [FK_PARALLON_SERVICE_GL_ACCOUNT_PdtsUser] FOREIGN KEY ([CREATED_BY_USER_ID]) REFERENCES [dbo].[PdtsUser] ([USER_ID]),
    CONSTRAINT [FK_PARALLON_SERVICE_GL_ACCOUNT_PdtsUser1] FOREIGN KEY ([UPDATED_BY_USER_ID]) REFERENCES [dbo].[PdtsUser] ([USER_ID])
);

