CREATE TABLE [dbo].[PCR_COID_FILTER] (
    [PCR_COID_FILTER_ID] INT         IDENTITY (1, 1) NOT NULL,
    [COID]               VARCHAR (5) NOT NULL,
    [IS_PRE]             BIT         CONSTRAINT [DF_PCR_COID_FILTER_IS_PRE] DEFAULT ((0)) NOT NULL,
    [IS_POST]            BIT         CONSTRAINT [DF_PCR_COID_FILTER_IS_POST] DEFAULT ((0)) NOT NULL,
    [ACTIVE]             BIT         CONSTRAINT [DF_PCR_COID_FILTER_ACTIVE] DEFAULT ((1)) NOT NULL,
    [CREATE_DATE]        DATETIME    CONSTRAINT [DF_PCR_COID_FILTER_CREATE_DATE] DEFAULT (getdate()) NOT NULL,
    [CREATED_BY_USER_ID] INT         NOT NULL,
    [UPDATE_DATE]        DATETIME    NULL,
    [UPDATED_BY_USER_ID] INT         NULL,
    CONSTRAINT [PK_PCR_COID_FILTER] PRIMARY KEY CLUSTERED ([PCR_COID_FILTER_ID] ASC),
    CONSTRAINT [FK_PCR_COID_FILTER_CreateUser] FOREIGN KEY ([CREATED_BY_USER_ID]) REFERENCES [dbo].[PdtsUser] ([USER_ID]),
    CONSTRAINT [FK_PCR_COID_FILTER_Facility] FOREIGN KEY ([COID]) REFERENCES [dbo].[Facility] ([COID]),
    CONSTRAINT [FK_PCR_COID_FILTER_UpdateUser] FOREIGN KEY ([UPDATED_BY_USER_ID]) REFERENCES [dbo].[PdtsUser] ([USER_ID])
);

