CREATE TABLE [dbo].[PCR_HOSPITAL_QUARTERLY_UPLOAD] (
    [PCR_HOSPITAL_QUARTERLY_UPLOAD_ID]    INT           IDENTITY (1, 1) NOT NULL,
    [PCR_HOSPITAL_QUARTERLY_CHECKLIST_ID] INT           NOT NULL,
    [FILE_NAME]                           VARCHAR (100) NOT NULL,
    [UPLOAD_DATE]                         DATETIME      CONSTRAINT [DF_PCR_HOSPITAL_QUARTERLY_UPLOAD_UPLOAD_DATE] DEFAULT (getdate()) NOT NULL,
    [UPLOADED_BY_USER_ID]                 INT           NOT NULL,
    [UPLOADED_BY_USER_NAME]               VARCHAR (100) NULL,
    [URL]                                 VARCHAR (200) NOT NULL,
    CONSTRAINT [PK_PCR_HOSPITAL_QUARTERLY_UPLOAD] PRIMARY KEY CLUSTERED ([PCR_HOSPITAL_QUARTERLY_UPLOAD_ID] ASC),
    CONSTRAINT [FK_PCR_HOSPITAL_QUARTERLY_UPLOAD_PCR_HOSPITAL_QUARTERLY_CHECKLIST] FOREIGN KEY ([PCR_HOSPITAL_QUARTERLY_CHECKLIST_ID]) REFERENCES [dbo].[PCR_HOSPITAL_QUARTERLY_CHECKLIST] ([PCR_HOSPITAL_QUARTERLY_CHECKLIST_ID])
);

