CREATE TABLE [dbo].[PCR_HOSPITAL_QUARTERLY_CHECKLIST] (
    [PCR_HOSPITAL_QUARTERLY_CHECKLIST_ID] INT            IDENTITY (1, 1) NOT NULL,
    [COID]                                VARCHAR (5)    NOT NULL,
    [SUB_COID]                            VARCHAR (5)    NOT NULL,
    [ACCOUNT]                             INT            NOT NULL,
    [QUARTER]                             TINYINT        NOT NULL,
    [YEAR]                                INT            NOT NULL,
    [IS_PRE]                              BIT            CONSTRAINT [DF_PCR_HOSPITAL_QUARTERLY_CHECKLIST_IS_PRE] DEFAULT ((0)) NOT NULL,
    [IS_POST]                             BIT            CONSTRAINT [DF_PCR_HOSPITAL_QUARTERLY_CHECKLIST_IS_POST] DEFAULT ((0)) NOT NULL,
    [VALIDATED]                           BIT            CONSTRAINT [DF_PCR_HOSPITAL_QUARTERLY_CHECKLIST_VALIDATED] DEFAULT ((0)) NOT NULL,
    [VALIDATE_USER_ID]                    INT            NULL,
    [VALIDATE_USER_DATE]                  DATETIME       NULL,
    [VALIDATE_USER_NAME]                  VARCHAR (50)   NULL,
    [REVIEWED]                            BIT            CONSTRAINT [DF_PCR_HOSPITAL_QUARTERLY_CHECKLIST_REVIEWED] DEFAULT ((0)) NOT NULL,
    [REVIEWED_USER_ID]                    INT            NULL,
    [REVIEWED_USER_DATE]                  DATETIME       NULL,
    [REVIEWED_USER_NAME]                  VARCHAR (50)   NULL,
    [CREATE_DATE]                         DATETIME       CONSTRAINT [DF_PCR_HOSPITAL_QUARTERLY_CHECKLIST_CREATE_DATE] DEFAULT (getdate()) NOT NULL,
    [COMMENT]                             VARCHAR (1000) NULL,
    [COMMENT_USER_ID]                     INT            NULL,
    [COMMENT_USER_NAME]                   VARCHAR (50)   NULL,
    [COMMENT_DATE]                        DATETIME       NULL,
    [DOCUMENT_NAME]                       VARCHAR (100)  NULL,
    [IS_DOCUMENTATION_REQUIRED]           BIT            CONSTRAINT [DF_PCR_HOSPITAL_QUARTERLY_CHECKLIST_IS_DOCUMENTATION_REQUIRED] DEFAULT ((0)) NOT NULL,
    [IS_COMMENT_REQUIRED]                 BIT            CONSTRAINT [DF_PCR_HOSPITAL_QUARTERLY_CHECKLIST_IS_COMMENT_REQUIRED] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_PCR_HOSPITAL_QUARTERLY_CHECKLIST] PRIMARY KEY CLUSTERED ([PCR_HOSPITAL_QUARTERLY_CHECKLIST_ID] ASC),
    CONSTRAINT [FK_PCR_HOSPITAL_QUARTERLY_CHECKLIST_Facility] FOREIGN KEY ([COID]) REFERENCES [dbo].[Facility] ([COID])
);

