CREATE TABLE [dbo].[PDTS_ROLE] (
    [PDTS_ROLE_ID] INT          IDENTITY (1, 1) NOT NULL,
    [NAME]         VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_PDTS_ROLES] PRIMARY KEY CLUSTERED ([PDTS_ROLE_ID] ASC)
);

