CREATE TABLE [dbo].[PDTS_USER_ROLE] (
    [PDTS_USER_ROLE_ID] INT         IDENTITY (1, 1) NOT NULL,
    [USER_ID]           INT         NOT NULL,
    [PDTS_ROLE_ID]      INT         NOT NULL,
    [COID]              VARCHAR (5) NOT NULL,
    CONSTRAINT [PK_PDTS_USER_ROLE] PRIMARY KEY CLUSTERED ([PDTS_USER_ROLE_ID] ASC),
    CONSTRAINT [FK_PDTS_USER_ROLE_Facility] FOREIGN KEY ([COID]) REFERENCES [dbo].[Facility] ([COID]),
    CONSTRAINT [FK_PDTS_USER_ROLE_PDTS_ROLE] FOREIGN KEY ([PDTS_ROLE_ID]) REFERENCES [dbo].[PDTS_ROLE] ([PDTS_ROLE_ID]),
    CONSTRAINT [FK_PDTS_USER_ROLE_PdtsUser] FOREIGN KEY ([USER_ID]) REFERENCES [dbo].[PdtsUser] ([USER_ID])
);

