CREATE TABLE [dbo].[PENDING_CHANGE_APPROVAL_MASTER] (
    [PENDING_CHANGE_APPROVAL_MASTER_ID] INT           NOT NULL,
    [APPROVAL_USER_ID]                  INT           NOT NULL,
    [ORDER_OF_APPROVAL]                 INT           NOT NULL,
    [APPROVED]                          BIT           CONSTRAINT [DF_PENDING_CHANGE_APPROVAL_MASTER_APPROVED] DEFAULT ((0)) NOT NULL,
    [APPROVED_DATE]                     DATETIME      NULL,
    [REJECTED]                          BIT           CONSTRAINT [DF_PENDING_CHANGE_APPROVAL_MASTER_REJECTED] DEFAULT ((0)) NOT NULL,
    [REJECTED_DATE]                     DATETIME      NULL,
    [REJECTED_REASON]                   VARCHAR (100) NULL,
    [IS_FINAL_APPROVER]                 BIT           CONSTRAINT [DF_PENDING_CHANGE_APPROVAL_MASTER_IS_FINAL_APPROVER] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_PENDING_CHANGE_APPROVAL_MASTER] PRIMARY KEY CLUSTERED ([PENDING_CHANGE_APPROVAL_MASTER_ID] ASC)
);

