CREATE TABLE [dbo].[PENDING_CHANGE_APPROVAL] (
    [PENDING_CHANGE_APPROVAL_ID] INT IDENTITY (1, 1) NOT NULL,
    [PENDING_CHANGE_ID]          INT NOT NULL,
    [USER_ID]                    INT NOT NULL,
    [ORDER_OF_APPROVAL]          INT NOT NULL,
    CONSTRAINT [PK_PENDING_CHANGE_APPROVAL] PRIMARY KEY CLUSTERED ([PENDING_CHANGE_APPROVAL_ID] ASC),
    CONSTRAINT [FK_PENDING_CHANGE_APPROVAL_PdtsUser] FOREIGN KEY ([USER_ID]) REFERENCES [dbo].[PdtsUser] ([USER_ID]),
    CONSTRAINT [FK_PENDING_CHANGE_APPROVAL_PENDING_CHANGE] FOREIGN KEY ([PENDING_CHANGE_ID]) REFERENCES [dbo].[PENDING_CHANGE] ([PENDING_CHANGE_ID])
);

