CREATE TABLE [dbo].[PERFORMANCE_IMPROVEMENT_FREQUENCY] (
    [PERFORMANCE_IMPROVEMENT_FREQUENCY_ID] INT          IDENTITY (1, 1) NOT NULL,
    [NAME]                                 VARCHAR (50) NULL,
    CONSTRAINT [PK_PERFORMANCE_IMPROVEMENT_FREQUENCY] PRIMARY KEY CLUSTERED ([PERFORMANCE_IMPROVEMENT_FREQUENCY_ID] ASC)
);

