CREATE TABLE [dbo].[PERFORMANCE_IMPROVEMENT_MINUTES] (
    [PERFORMANCE_IMPROVEMENT_MINUTES_ID] INT            IDENTITY (1, 1) NOT NULL,
    [PERFORMANCE_IMPROVEMENT_IDEA_ID]    INT            NOT NULL,
    [MINUTES]                            VARCHAR (3000) NOT NULL,
    [MINUTES_DATE]                       DATETIME       NOT NULL,
    [CREATED_BY_USER_ID]                 INT            NOT NULL,
    CONSTRAINT [PK_PERFORMANCE_IMPROVEMENT_MINUTES] PRIMARY KEY CLUSTERED ([PERFORMANCE_IMPROVEMENT_MINUTES_ID] ASC),
    CONSTRAINT [FK_PERFORMANCE_IMPROVEMENT_MINUTES_PdtsUser] FOREIGN KEY ([CREATED_BY_USER_ID]) REFERENCES [dbo].[PdtsUser] ([USER_ID]),
    CONSTRAINT [FK_PERFORMANCE_IMPROVEMENT_MINUTES_PERFORMANCE_IMPROVEMENT_IDEA] FOREIGN KEY ([PERFORMANCE_IMPROVEMENT_IDEA_ID]) REFERENCES [dbo].[PERFORMANCE_IMPROVEMENT_IDEA] ([PERFORMANCE_IMPROVEMENT_IDEA_ID])
);

