CREATE TABLE [dbo].[PERFORMANCE_IMPROVEMENT_COMPLETION_STATUS] (
    [PERFORMANCE_IMPROVEMENT_COMPLETION_STATUS_ID] INT          IDENTITY (1, 1) NOT NULL,
    [NAME]                                         VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_PERFORMANCE_IMPROVEMENT_STATUS] PRIMARY KEY CLUSTERED ([PERFORMANCE_IMPROVEMENT_COMPLETION_STATUS_ID] ASC)
);

