CREATE TABLE [dbo].[PERFORMANCE_IMPROVEMENT_ENTRY] (
    [PERFORMANCE_IMPROVEMENT_ENTRY_ID] INT      IDENTITY (1, 1) NOT NULL,
    [PERFORMANCE_IMPROVEMENT_IDEA_ID]  INT      NOT NULL,
    [MONTH]                            TINYINT  NOT NULL,
    [YEAR]                             INT      NOT NULL,
    [QUARTER]                          TINYINT  NOT NULL,
    [ACTUAL_SAVINGS]                   MONEY    CONSTRAINT [DF_PERFORMANCE_IMPROVEMENT_ENTRY_ACTUAL_SAVINGS] DEFAULT ((0)) NOT NULL,
    [CREATE_DATE]                      DATETIME CONSTRAINT [DF_PERFORMANCE_IMPROVEMENT_ENTRY_CREATE_DATE] DEFAULT (getdate()) NOT NULL,
    [CREATED_BY_USER_ID]               INT      NOT NULL,
    [UPDATE_DATE]                      DATETIME NULL,
    [UPDATED_BY_USER_ID]               INT      NULL,
    CONSTRAINT [PK_PERFORMANCE_IMPROVEMENT_ENTRY] PRIMARY KEY CLUSTERED ([PERFORMANCE_IMPROVEMENT_ENTRY_ID] ASC),
    CONSTRAINT [FK_PERFORMANCE_IMPROVEMENT_ENTRY_CreateUser] FOREIGN KEY ([CREATED_BY_USER_ID]) REFERENCES [dbo].[PdtsUser] ([USER_ID]),
    CONSTRAINT [FK_PERFORMANCE_IMPROVEMENT_ENTRY_PERFORMANCE_IMPROVEMENT_IDEA] FOREIGN KEY ([PERFORMANCE_IMPROVEMENT_IDEA_ID]) REFERENCES [dbo].[PERFORMANCE_IMPROVEMENT_IDEA] ([PERFORMANCE_IMPROVEMENT_IDEA_ID]),
    CONSTRAINT [FK_PERFORMANCE_IMPROVEMENT_ENTRY_UpdateUser] FOREIGN KEY ([UPDATED_BY_USER_ID]) REFERENCES [dbo].[PdtsUser] ([USER_ID])
);

