CREATE TABLE [dbo].[PERFORMANCE_IMPROVEMENT_MILESTONE] (
    [PERFORMANCE_IMPROVEMENT_MILESTONE_ID] INT            IDENTITY (1, 1) NOT NULL,
    [PERFORMANCE_IMPROVEMENT_IDEA_ID]      INT            NOT NULL,
    [STEP_NUMBER]                          INT            NOT NULL,
    [DESCRIPTION]                          VARCHAR (1000) NOT NULL,
    [RESPONSIBLE_PARTY]                    VARCHAR (50)   NULL,
    [DUE_DATE]                             DATETIME       NOT NULL,
    [CREATED_BY_USER_ID]                   INT            NOT NULL,
    [CREATE_DATE]                          DATETIME       CONSTRAINT [DF_PERFORMANCE_IMPROVEMENT_MILESTONE_CREATE_DATE] DEFAULT (getdate()) NOT NULL,
    [UPDATED_BY_USER_ID]                   INT            NULL,
    [UPDATE_DATE]                          DATETIME       NULL,
    CONSTRAINT [PK_PERFORMANCE_IMPROVEMENT_MILESTONE] PRIMARY KEY CLUSTERED ([PERFORMANCE_IMPROVEMENT_MILESTONE_ID] ASC),
    CONSTRAINT [FK_PERFORMANCE_IMPROVEMENT_MILESTONE_PdtsUser] FOREIGN KEY ([CREATED_BY_USER_ID]) REFERENCES [dbo].[PdtsUser] ([USER_ID]),
    CONSTRAINT [FK_PERFORMANCE_IMPROVEMENT_MILESTONE_PdtsUser1] FOREIGN KEY ([UPDATED_BY_USER_ID]) REFERENCES [dbo].[PdtsUser] ([USER_ID]),
    CONSTRAINT [FK_PERFORMANCE_IMPROVEMENT_MILESTONE_PERFORMANCE_IMPROVEMENT_IDEA] FOREIGN KEY ([PERFORMANCE_IMPROVEMENT_IDEA_ID]) REFERENCES [dbo].[PERFORMANCE_IMPROVEMENT_IDEA] ([PERFORMANCE_IMPROVEMENT_IDEA_ID])
);

