CREATE TABLE [dbo].[PERFORMANCE_IMPROVEMENT_PAYOFF_QUADRANT] (
    [PERFORMANCE_IMPROVEMENT_PAYOFF_QUADRANT_ID] INT          IDENTITY (1, 1) NOT NULL,
    [NAME]                                       VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_PERFORMANCE_IMPROVEMENT_PAYOFF_QUADRANT] PRIMARY KEY CLUSTERED ([PERFORMANCE_IMPROVEMENT_PAYOFF_QUADRANT_ID] ASC)
);

