CREATE TABLE [dbo].[PERFORMANCE_IMPROVEMENT_IDEA_STATUS] (
    [PERFOMANCE_IMPROVEMENT_IDEA_STATUS_ID] INT          IDENTITY (1, 1) NOT NULL,
    [NAME]                                  VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_PERFORMANCE_IMPROVEMENT_IDEA_STATUS] PRIMARY KEY CLUSTERED ([PERFOMANCE_IMPROVEMENT_IDEA_STATUS_ID] ASC)
);

