CREATE TABLE [dbo].[PERFORMANCE_IMPROVEMENT_SAVINGS] (
    [PERFORMANCE_IMPROVEMENT_SAVINGS_ID] INT      IDENTITY (1, 1) NOT NULL,
    [PERFORMANCE_IMPROVEMENT_IDEA_ID]    INT      NOT NULL,
    [GL_DEPARTMENT_ID]                   INT      NOT NULL,
    [GL_SUB_ACCOUNT_ID]                  INT      NOT NULL,
    [SAVINGS]                            MONEY    NOT NULL,
    [CREATED_BY_USER_ID]                 INT      NOT NULL,
    [CREATE_DATE]                        DATETIME CONSTRAINT [DF_PERFORMANCE_IMPROVEMENT_SAVINGS_CREATE_DATE] DEFAULT (getdate()) NOT NULL,
    [UPDATED_BY_USER_ID]                 INT      NULL,
    [UPDATE_DATE]                        DATETIME NULL,
    CONSTRAINT [PK_PERFORMANCE_IMPROVEMENT_SAVINGS] PRIMARY KEY CLUSTERED ([PERFORMANCE_IMPROVEMENT_SAVINGS_ID] ASC),
    CONSTRAINT [FK_PERFORMANCE_IMPROVEMENT_SAVINGS_GL_DEPARTMENT] FOREIGN KEY ([GL_DEPARTMENT_ID]) REFERENCES [dbo].[GL_DEPARTMENT] ([GL_DEPARTMENT_ID]),
    CONSTRAINT [FK_PERFORMANCE_IMPROVEMENT_SAVINGS_GL_SUB_ACCOUNT] FOREIGN KEY ([GL_SUB_ACCOUNT_ID]) REFERENCES [dbo].[GL_SUB_ACCOUNT] ([GL_SUB_ACCOUNT_ID]),
    CONSTRAINT [FK_PERFORMANCE_IMPROVEMENT_SAVINGS_PdtsUser] FOREIGN KEY ([CREATED_BY_USER_ID]) REFERENCES [dbo].[PdtsUser] ([USER_ID]),
    CONSTRAINT [FK_PERFORMANCE_IMPROVEMENT_SAVINGS_PdtsUser1] FOREIGN KEY ([UPDATED_BY_USER_ID]) REFERENCES [dbo].[PdtsUser] ([USER_ID]),
    CONSTRAINT [FK_PERFORMANCE_IMPROVEMENT_SAVINGS_PERFORMANCE_IMPROVEMENT_IDEA] FOREIGN KEY ([PERFORMANCE_IMPROVEMENT_IDEA_ID]) REFERENCES [dbo].[PERFORMANCE_IMPROVEMENT_IDEA] ([PERFORMANCE_IMPROVEMENT_IDEA_ID])
);

