CREATE TABLE [dbo].[PHYSICIAN_SCORECARD_CATEGORY] (
    [PHYSICIAN_SCORECARD_CATEGORY_ID] INT          IDENTITY (1, 1) NOT NULL,
    [NAME]                            VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_PHYSICIAN_SCORECARD_CATEGORY] PRIMARY KEY CLUSTERED ([PHYSICIAN_SCORECARD_CATEGORY_ID] ASC)
);

