CREATE TABLE [dbo].[PHYSICIAN_SCORECARD_POINTS] (
    [PHYSICIAN_SCORECARD_POINTS_ID]   INT         IDENTITY (1, 1) NOT NULL,
    [COID]                            VARCHAR (5) NOT NULL,
    [PHYSICIAN_SCORECARD_CATEGORY_ID] INT         NOT NULL,
    [POINTS]                          INT         NOT NULL,
    [YEAR]                            INT         NOT NULL,
    [QUARTER]                         INT         NOT NULL,
    CONSTRAINT [PK_PHYSICIAN_SCORECARD_POINTS] PRIMARY KEY CLUSTERED ([PHYSICIAN_SCORECARD_POINTS_ID] ASC),
    CONSTRAINT [FK_PHYSICIAN_SCORECARD_POINTS_Facility] FOREIGN KEY ([COID]) REFERENCES [dbo].[Facility] ([COID]),
    CONSTRAINT [FK_PHYSICIAN_SCORECARD_POINTS_PHYSICIAN_SCORECARD_CATEGORY] FOREIGN KEY ([PHYSICIAN_SCORECARD_CATEGORY_ID]) REFERENCES [dbo].[PHYSICIAN_SCORECARD_CATEGORY] ([PHYSICIAN_SCORECARD_CATEGORY_ID])
);

