CREATE TABLE [dbo].[PRIMARY_CARE_PRACTICE_REVENUE] (
    [PRIMARY_CARE_PRACTICE_REVENUE_ID] INT          IDENTITY (1, 1) NOT NULL,
    [NAME]                             VARCHAR (50) NOT NULL,
    [SCORE]                            TINYINT      CONSTRAINT [DF_PRIMARY_CARE_PRACTICE_REVENUE_SCORE] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_PRIMARY_CARE_PRACTICE_REVENUE] PRIMARY KEY CLUSTERED ([PRIMARY_CARE_PRACTICE_REVENUE_ID] ASC)
);

