CREATE TABLE [dbo].[PRIMARY_CARE_STRATEGY_CATEGORIES] (
    [PRIMARY_STRATEGY_CATEGORY_ID] INT           IDENTITY (1, 1) NOT NULL,
    [NAME]                         VARCHAR (100) NOT NULL,
    CONSTRAINT [PK_PRIMARY_CARE_STRATEGY_CATEGORIES] PRIMARY KEY CLUSTERED ([PRIMARY_STRATEGY_CATEGORY_ID] ASC)
);

