CREATE TABLE [dbo].[PRIMARY_CARE_YEARS_IN_PRACTICE] (
    [PRIMARY_CARE_YEARS_IN_PRACTICE_ID] INT          IDENTITY (1, 1) NOT NULL,
    [NAME]                              VARCHAR (50) NOT NULL,
    [SCORE]                             TINYINT      CONSTRAINT [DF_PRIMARY_CARE_YEARS_IN_PRACTICE_SCORE] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_PRIMARY_CARE_YEARS_IN_PRACTICE] PRIMARY KEY CLUSTERED ([PRIMARY_CARE_YEARS_IN_PRACTICE_ID] ASC)
);

