CREATE TABLE [dbo].[PRIMARY_CARE_OTHER_RISK] (
    [PRIMARY_CARE_OTHER_RISK_ID] INT          IDENTITY (1, 1) NOT NULL,
    [NAME]                       VARCHAR (50) NOT NULL,
    [SCORE]                      TINYINT      CONSTRAINT [DF_PRIMARY_CARE_OTHER_RISK_SCORE] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_PRIMARY_CARE_OTHER_RISK] PRIMARY KEY CLUSTERED ([PRIMARY_CARE_OTHER_RISK_ID] ASC)
);

