CREATE TABLE [dbo].[PRIMARY_CARE_AGE_BAND] (
    [PRIMARY_CARE_AGE_BAND_ID] INT     IDENTITY (1, 1) NOT NULL,
    [AGE_BAND_MINIMUM]         INT     NOT NULL,
    [AGE_BAND_MAXIMUM]         INT     NOT NULL,
    [SCORE]                    TINYINT NOT NULL,
    CONSTRAINT [PK_PRIMARY_CARE_AGE_BAND] PRIMARY KEY CLUSTERED ([PRIMARY_CARE_AGE_BAND_ID] ASC)
);

