CREATE TABLE [dbo].[PRIMARY_CARE_SERVICE_AREA] (
    [PRIMARY_CARE_SERVICE_AREA_ID] INT          IDENTITY (1, 1) NOT NULL,
    [NAME]                         VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_PRIMARY_CARE_STRATEGY_SERVICE_AREA_ID] PRIMARY KEY CLUSTERED ([PRIMARY_CARE_SERVICE_AREA_ID] ASC)
);

