CREATE TABLE [dbo].[PRIMARY_CARE_CLINIC_TYPES] (
    [PRIMARY_CARE_CLINIC_TYPE_ID] INT          IDENTITY (1, 1) NOT NULL,
    [NAME]                        VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_CLINIC_TYPES] PRIMARY KEY CLUSTERED ([PRIMARY_CARE_CLINIC_TYPE_ID] ASC)
);

