CREATE TABLE [dbo].[PRIMARY_CARE_SERVICE_TYPES] (
    [PRIMARY_SERVICE_TYPE_ID] INT           IDENTITY (1, 1) NOT NULL,
    [NAME]                    VARCHAR (100) NULL,
    CONSTRAINT [PK_PRIMARY_SERVICE_AREA_PCP_SUPPLY] PRIMARY KEY CLUSTERED ([PRIMARY_SERVICE_TYPE_ID] ASC)
);

