CREATE TABLE [dbo].[PRIMARY_CARE_AFFILIATION] (
    [PRIMARY_CARE_AFFILIATION_ID] INT          IDENTITY (1, 1) NOT NULL,
    [NAME]                        VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_PRIMARY_CARE_AFFILIATION] PRIMARY KEY CLUSTERED ([PRIMARY_CARE_AFFILIATION_ID] ASC)
);

