CREATE TABLE [dbo].[ProjectedSurgeries] (
    [PROJECTED_SURGERIES_ID]        INT      IDENTITY (1, 1) NOT NULL,
    [PDTS_PROVIDER_ID]              INT      NOT NULL,
    [YEAR]                          INT      NOT NULL,
    [SURGICAL_TYPE_ID]              INT      NOT NULL,
    [PERIOD09_INPATIENT_SURGERIES]  INT      NOT NULL,
    [PERIOD10_INPATIENT_SURGERIES]  INT      NOT NULL,
    [PERIOD11_INPATIENT_SURGERIES]  INT      NOT NULL,
    [PERIOD12_INPATIENT_SURGERIES]  INT      NOT NULL,
    [PERIOD09_OUTPATIENT_SURGERIES] INT      NOT NULL,
    [PERIOD10_OUTPATIENT_SURGERIES] INT      NOT NULL,
    [PERIOD11_OUTPATIENT_SURGERIES] INT      NOT NULL,
    [PERIOD12_OUTPATIENT_SURGERIES] INT      NOT NULL,
    [CREATE_DATE]                   DATETIME CONSTRAINT [DF_ProjectedSurgeries_CREATE_DATE] DEFAULT (getdate()) NOT NULL,
    [CREATED_BY_USER_ID]            INT      NOT NULL,
    [UPDATE_DATE]                   DATETIME NULL,
    [UPDATED_BY_USER_ID]            INT      NULL,
    CONSTRAINT [PK_ProjectedSurgeries] PRIMARY KEY CLUSTERED ([PROJECTED_SURGERIES_ID] ASC),
    CONSTRAINT [FK_ProjectedSurgeries_PdtsUser] FOREIGN KEY ([CREATED_BY_USER_ID]) REFERENCES [dbo].[PdtsUser] ([USER_ID]),
    CONSTRAINT [FK_ProjectedSurgeries_PdtsUser1] FOREIGN KEY ([UPDATED_BY_USER_ID]) REFERENCES [dbo].[PdtsUser] ([USER_ID]),
    CONSTRAINT [FK_ProjectedSurgeries_Provider] FOREIGN KEY ([PDTS_PROVIDER_ID]) REFERENCES [dbo].[Provider] ([PDTS_PROVIDER_ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_ProjectedSurgeries_Surgical_Type] FOREIGN KEY ([SURGICAL_TYPE_ID]) REFERENCES [dbo].[Surgical_Type] ([SURGICAL_TYPE_ID])
);

