CREATE TABLE [dbo].[PROVIDER_YEARS_EXPERIENCE_REQUIRED] (
    [YEARS_EXPERIENCE_REQUIRED_ID] INT          IDENTITY (1, 1) NOT NULL,
    [NAME]                         VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_PROVIDER_YEARS_EXPERIENCE_REQUIRED] PRIMARY KEY CLUSTERED ([YEARS_EXPERIENCE_REQUIRED_ID] ASC)
);

