CREATE TABLE [dbo].[Provider_History] (
    [PROVIDER_HISTORY_ID]                  INT            IDENTITY (1, 1) NOT NULL,
    [PDTS_PROVIDER_ID]                     INT            NOT NULL,
    [PROVIDER_ID]                          INT            NOT NULL,
    [COID]                                 VARCHAR (5)    NOT NULL,
    [LAST_NAME]                            VARCHAR (50)   NOT NULL,
    [FIRST_NAME]                           VARCHAR (50)   NULL,
    [MIDDLE_NAME]                          VARCHAR (50)   NULL,
    [FULL_NAME]                            VARCHAR (150)  NOT NULL,
    [DOB]                                  DATETIME       NULL,
    [SPECIALTY_ID]                         INT            NULL,
    [START_DATE]                           DATETIME       NULL,
    [LEFT_DATE]                            DATETIME       NULL,
    [PHYSICIAN_REASON_ID]                  INT            NULL,
    [ACTIVE_FOR_ADMITS]                    BIT            NOT NULL,
    [ACTIVE_FOR_SURGERIES]                 BIT            NOT NULL,
    [HOSPITALIST]                          BIT            NOT NULL,
    [LOCUM]                                BIT            NOT NULL,
    [ADMITS_TO_HOSPITALIST]                BIT            NOT NULL,
    [INDEPENDENT]                          BIT            NOT NULL,
    [EMPLOYED]                             BIT            NOT NULL,
    [REVENUE_GUARANTEE]                    BIT            NOT NULL,
    [BUDGET_PROVIDER_ID]                   INT            NULL,
    [EMPLOYEE_PHYSICIAN_COID]              VARCHAR (5)    NULL,
    [STARTING_MONTH]                       TINYINT        NOT NULL,
    [PROVIDER_POSITION_STATUS_ID]          INT            NULL,
    [CREATE_DATE]                          DATETIME       NOT NULL,
    [CREATED_BY_USER_ID]                   INT            NOT NULL,
    [UPDATE_DATE]                          DATETIME       NULL,
    [UPDATED_BY_USER_ID]                   INT            NULL,
    [OTHER_REASON_TEXT]                    VARCHAR (500)  NULL,
    [RECRUITING]                           BIT            NULL,
    [PROVIDER_VOLUME_STATUS_ID]            INT            NULL,
    [PROVIDER_CONTRACT_TYPE_ID]            INT            NULL,
    [APPROVED_FOR_SCORECARD]               BIT            NOT NULL,
    [PHYSICIAN_GROUP]                      VARCHAR (50)   NULL,
    [SIGNED_DATE]                          DATETIME       NULL,
    [PROJECTED_START_DATE]                 DATETIME       NULL,
    [ON_HOLD]                              BIT            NOT NULL,
    [BUDGETED_START_DATE]                  DATETIME       NULL,
    [DIVISION_PRIORITY]                    BIT            NOT NULL,
    [WATCH_LIST]                           BIT            NOT NULL,
    [PROVIDER_RECRUITMENT_STATUS_ID]       INT            NULL,
    [PROVIDER_TITLE_ID]                    INT            NULL,
    [NPI]                                  BIGINT         NULL,
    [SSN]                                  BIGINT         NULL,
    [MEDICARE]                             VARCHAR (40)   NULL,
    [MEDICAID]                             VARCHAR (40)   NULL,
    [BLUECROSS]                            VARCHAR (40)   NULL,
    [PROVIDER_SENIOR_DIRECTOR_ID]          INT            NULL,
    [PROVIDER_REGIONAL_DIRECTOR_ID]        INT            NULL,
    [PROVIDER_VP_PHYSICIAN_SERVICES_ID]    INT            NULL,
    [PROVIDER_DEPT_ID]                     INT            NULL,
    [PROVIDER_OVERHEAD_DEPT_ID]            INT            NULL,
    [NURSE_DEPT_ID]                        INT            NULL,
    [EMPLOYEE_PHYSICIAN_COID_NAME]         VARCHAR (50)   NULL,
    [GROUP_NPI]                            BIGINT         NULL,
    [ECW_ID]                               BIGINT         NULL,
    [CLINIC_DEPT_ID]                       INT            NULL,
    [ACTIVE]                               BIT            NOT NULL,
    [RECORD_START_DATE]                    DATETIME       NULL,
    [RECORD_END_DATE]                      DATETIME       NULL,
    [PROVIDER_RECRUITMENT_STATUS_DATE]     DATETIME       NULL,
    [MATERIAL_DOC]                         BIT            NULL,
    [MATERIAL_PHYSICIAN_REASON_ID]         INT            NULL,
    [COURTESY]                             BIT            CONSTRAINT [DF_Provider_History_COURTESY] DEFAULT ((0)) NOT NULL,
    [PROVIDER_AFFILIATION_ID]              INT            NULL,
    [FTE_ASSESSMENT]                       DECIMAL (2, 1) NULL,
    [PRIMARY_CARE_COMMUNITY_ACCEPTANCE_ID] INT            NULL,
    [PRIMARY_CARE_OTHER_RISK_ID]           INT            NULL,
    [PRIMARY_CARE_PRACTICE_REVENUE_ID]     INT            NULL,
    [PRIMARY_CARE_YEARS_IN_PRACTICE_ID]    INT            NULL,
    [RISK_SCORE]                           DECIMAL (2, 1) NULL,
    [RESPONSIBLE_PDTS_PROVIDER_ID]         INT            NULL,
    [EMAIL_ADDRESS]                        VARCHAR (50)   NULL,
    [DEA_NUMBER]                           VARCHAR (20)   NULL,
    [PRIMARY_ADDRESS_LINE1]                VARCHAR (50)   NULL,
    [PRIMARY_ADDRESS_LINE2]                VARCHAR (50)   NULL,
    [PRIMARY_ADDRESS_CITY]                 VARCHAR (50)   NULL,
    [PRIMARY_ADDRESS_STATE_ID]             INT            NULL,
    [PRIMARY_ADDRESS_ZIP]                  VARCHAR (9)    NULL,
    [PRIMARY_PHONE_NUMBER]                 VARCHAR (10)   NULL,
    [PROVIDER_AL_CODE_ID]                  INT            NULL,
    [SATISFACTION_SURVEY_PASSWORD]         VARCHAR (50)   NULL,
    [INCLUDE_IN_SAT_SURVEY]                BIT            CONSTRAINT [DF_Provider_History_INCLUDE_IN_SAT_SURVEY] DEFAULT ((0)) NOT NULL,
    [GENDER]                               CHAR (1)       NULL,
    [PROVIDER_TYPE_ID]                     INT            NULL,
    [SATISFACTION_SURVEY_MATCH_ID]         VARCHAR (50)   NULL,
    [PROVIDER_STAFF_STATUS_ID]             INT            NULL,
    [PROVIDER_DIRECTOR_ID]                 INT            NULL,
    [SRC_ID]                               INT            NULL,
    [SUM_NUMBER]                           INT            NULL,
    [PROVIDER_COUNT]                       INT            NULL,
    [JOINING_AN_EXISTING_PRACTICE]         BIT            NULL,
    [REPLACING_AN_EXISTING_PROVIDER]       BIT            NULL,
    [PROVIDER_BEING_REPLACED]              VARCHAR (100)  NULL,
    [PRIOR_MALPRACTICE_COVERAGE_AMOUNT]    MONEY          NULL,
    [PRIOR_MALPRACTICE_COVERAGE_CARRIER]   VARCHAR (100)  NULL,
    [BUDGETED]                             BIT            NULL,
    [NPPES_LOGIN]                          VARCHAR (50)   NULL,
    [NPPES_PASSWORD]                       VARCHAR (50)   NULL,
    [PROVIDER_LINE_OF_BUSINESS_ID]         INT            NULL,
    [EMPLOYED_PROVIDER_STATUS_ID]          INT            NULL,
    [SPECIALTY_TYPE_ID]                    INT            NULL,
    [PROVIDER_BILL_TYPE_ID]                INT            NULL
);

