CREATE TABLE [dbo].[PROVIDER_PRACTICE_MANAGEMENT_SYSTEM] (
    [PROVIDER_PRACTICE_MANAGMENT_SYSTEM_ID] INT          IDENTITY (1, 1) NOT NULL,
    [NAME]                                  VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_PROVIDER_PRACTICE_MANAGEMENT_SYSTEM] PRIMARY KEY CLUSTERED ([PROVIDER_PRACTICE_MANAGMENT_SYSTEM_ID] ASC)
);

