CREATE TABLE [dbo].[PROVIDER_AFFILIATION] (
    [PROVIDER_AFFILIATION_ID] INT          IDENTITY (1, 1) NOT NULL,
    [NAME]                    VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_PROVIDER_AFFILIATION] PRIMARY KEY CLUSTERED ([PROVIDER_AFFILIATION_ID] ASC)
);

