CREATE TABLE [dbo].[PROVIDER_PRACTICE_STRUCTURE_SPACE] (
    [PROVIDER_PRACTICE_STRUCTURE_SPACE_ID] INT          IDENTITY (1, 1) NOT NULL,
    [NAME]                                 VARCHAR (50) NULL,
    CONSTRAINT [PK_PROVIDER_PRACTICE_STRUCTURE_SPACE] PRIMARY KEY CLUSTERED ([PROVIDER_PRACTICE_STRUCTURE_SPACE_ID] ASC)
);

