CREATE TABLE [dbo].[PROVIDER_AL_CODE] (
    [PROVIDER_AL_CODE_ID] INT          IDENTITY (1, 1) NOT NULL,
    [NAME]                VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_PROVIDER_AL_CODE] PRIMARY KEY CLUSTERED ([PROVIDER_AL_CODE_ID] ASC)
);

