CREATE TABLE [dbo].[PROVIDER_AUDIT_TYPE] (
    [PROVIDER_AUDIT_TYPE_ID] INT          IDENTITY (1, 1) NOT NULL,
    [NAME]                   VARCHAR (50) NOT NULL,
    [CREATE_DATE]            DATETIME     CONSTRAINT [DF_PROVIDER_AUDIT_TYPE_CREATE_DATE] DEFAULT (getdate()) NOT NULL,
    [CREATED_BY_USER_ID]     INT          NOT NULL,
    [UPDATE_DATE]            DATETIME     NULL,
    [UPDATED_BY_USER_ID]     INT          NULL,
    [TYPE_NUMER]             TINYINT      NOT NULL,
    CONSTRAINT [PK_PROVIDER_AUDIT_TYPE] PRIMARY KEY CLUSTERED ([PROVIDER_AUDIT_TYPE_ID] ASC),
    CONSTRAINT [FK_PROVIDER_AUDIT_TYPE_CreateUser] FOREIGN KEY ([CREATED_BY_USER_ID]) REFERENCES [dbo].[PdtsUser] ([USER_ID]),
    CONSTRAINT [FK_PROVIDER_AUDIT_TYPE_UpdateUser] FOREIGN KEY ([UPDATED_BY_USER_ID]) REFERENCES [dbo].[PdtsUser] ([USER_ID])
);

