CREATE TABLE [dbo].[PROVIDER_AUDIT_OCCURANCE] (
    [PROVIDER_AUDIT_OCCURANCE_ID] INT          IDENTITY (1, 1) NOT NULL,
    [NAME]                        VARCHAR (50) NOT NULL,
    [CREATE_DATE]                 DATETIME     CONSTRAINT [DF_PROVIDER_AUDIT_OCCURANCE_CREATE_DATE] DEFAULT (getdate()) NOT NULL,
    [CREATED_BY_USER_ID]          INT          NOT NULL,
    [UPDATE_DATE]                 DATETIME     NULL,
    [UPDATED_BY_USER_ID]          INT          NULL,
    CONSTRAINT [PK_PROVIDER_AUDIT_OCCURANCE] PRIMARY KEY CLUSTERED ([PROVIDER_AUDIT_OCCURANCE_ID] ASC),
    CONSTRAINT [FK_PROVIDER_AUDIT_OCCURANCE_CreateUser] FOREIGN KEY ([CREATED_BY_USER_ID]) REFERENCES [dbo].[PdtsUser] ([USER_ID]),
    CONSTRAINT [FK_PROVIDER_AUDIT_OCCURANCE_UpdateUser] FOREIGN KEY ([UPDATED_BY_USER_ID]) REFERENCES [dbo].[PdtsUser] ([USER_ID])
);

