CREATE TABLE [dbo].[PROVIDER_PRACTICE_ADDRESS_XREF] (
    [PROVIDER_PRACTICE_ADDRESS_XREF_ID] INT      IDENTITY (1, 1) NOT NULL,
    [PROVIDER_PRACTICE_ID]              INT      NOT NULL,
    [PROVIDER_PRACTICE_ADDRESS_ID]      INT      NOT NULL,
    [ACTIVE]                            BIT      CONSTRAINT [DF_PROVIDER_PRACTICE_ADDRESS_XREF_ACTIVE] DEFAULT ((0)) NOT NULL,
    [PREFERRED]                         BIT      CONSTRAINT [DF_PROVIDER_PRACTICE_ADDRESS_XREF_PREFERRED] DEFAULT ((0)) NOT NULL,
    [CREATED_BY_USER_ID]                INT      NOT NULL,
    [CREATE_DATE]                       DATETIME CONSTRAINT [DF_PROVIDER_PRACTICE_ADDRESS_XREF_CREATE_DATE] DEFAULT (getdate()) NOT NULL,
    [UPDATED_BY_USER_ID]                INT      NULL,
    [UPDATE_DATE]                       DATETIME NULL,
    CONSTRAINT [PK_PROVIDER_PRACTICE_ADDRESS_XREF] PRIMARY KEY CLUSTERED ([PROVIDER_PRACTICE_ADDRESS_XREF_ID] ASC),
    CONSTRAINT [FK_PROVIDER_PRACTICE_ADDRESS_XREF_CreateUser] FOREIGN KEY ([CREATED_BY_USER_ID]) REFERENCES [dbo].[PdtsUser] ([USER_ID]),
    CONSTRAINT [FK_PROVIDER_PRACTICE_ADDRESS_XREF_ProviderPractice] FOREIGN KEY ([PROVIDER_PRACTICE_ID]) REFERENCES [dbo].[ProviderPractice] ([PROVIDER_PRACTICE_ID]),
    CONSTRAINT [FK_PROVIDER_PRACTICE_ADDRESS_XREF_ProviderPracticeAddress] FOREIGN KEY ([PROVIDER_PRACTICE_ADDRESS_ID]) REFERENCES [dbo].[ProviderPracticeAddress] ([PROVIDER_PRACTICE_ADDRESS_ID]),
    CONSTRAINT [FK_PROVIDER_PRACTICE_ADDRESS_XREF_UpdateUser] FOREIGN KEY ([UPDATED_BY_USER_ID]) REFERENCES [dbo].[PdtsUser] ([USER_ID])
);

