CREATE TABLE [dbo].[PROVIDER_PRACTICE_STRUCTURE_AGREEMENT_TYPE] (
    [PROVIDER_PRACTICE_STRUCTURE_AGREEMENT_TYPE_ID] INT          IDENTITY (1, 1) NOT NULL,
    [NAME]                                          VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_PROVIDER_PRACTICE_STRUCTURE_AGREEMENT_TYPE] PRIMARY KEY CLUSTERED ([PROVIDER_PRACTICE_STRUCTURE_AGREEMENT_TYPE_ID] ASC)
);

