CREATE TABLE [dbo].[PROVIDER_LINE_OF_BUSINESS] (
    [PROVIDER_LINE_OF_BUSINESS_ID] INT          IDENTITY (1, 1) NOT NULL,
    [NAME]                         VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_PROVIDER_LINE_OF_BUSINESS] PRIMARY KEY CLUSTERED ([PROVIDER_LINE_OF_BUSINESS_ID] ASC)
);

