CREATE TABLE [dbo].[PROVIDER_PROVIDER_PRACTICE_ADDRESS_XREF] (
    [PROVIDER_PROVIDER_PRACTICE_ADDRESS_XREF_ID] INT      IDENTITY (1, 1) NOT NULL,
    [PDTS_PROVIDER_ID]                           INT      NOT NULL,
    [PROVIDER_PRACTICE_ADDRESS_ID]               INT      NOT NULL,
    [PREFERRED]                                  BIT      CONSTRAINT [DF_PROVIDER_PROVIDER_PRACTICE_ADDRESS_XREF_PREFERRED] DEFAULT ((0)) NOT NULL,
    [CREATED_BY_USER_ID]                         INT      NOT NULL,
    [CREATE_DATE]                                DATETIME CONSTRAINT [DF_PROVIDER_PROVIDER_PRACTICE_ADDRESS_XREF_CREATE_DATE] DEFAULT (getdate()) NOT NULL,
    [UPDATED_BY_USER_ID]                         INT      NULL,
    [UPDATE_DATE]                                DATETIME NULL,
    CONSTRAINT [PK_PROVIDER_PROVIDER_PRACTICE_ADDRESS_XREF] PRIMARY KEY CLUSTERED ([PROVIDER_PROVIDER_PRACTICE_ADDRESS_XREF_ID] ASC),
    CONSTRAINT [FK_PROVIDER_PROVIDER_PRACTICE_ADDRESS_XREF_CreateUser] FOREIGN KEY ([CREATED_BY_USER_ID]) REFERENCES [dbo].[PdtsUser] ([USER_ID]),
    CONSTRAINT [FK_PROVIDER_PROVIDER_PRACTICE_ADDRESS_XREF_Provider] FOREIGN KEY ([PDTS_PROVIDER_ID]) REFERENCES [dbo].[Provider] ([PDTS_PROVIDER_ID]),
    CONSTRAINT [FK_PROVIDER_PROVIDER_PRACTICE_ADDRESS_XREF_ProviderPracticeAddress] FOREIGN KEY ([PROVIDER_PRACTICE_ADDRESS_ID]) REFERENCES [dbo].[ProviderPracticeAddress] ([PROVIDER_PRACTICE_ADDRESS_ID]),
    CONSTRAINT [FK_PROVIDER_PROVIDER_PRACTICE_ADDRESS_XREF_UpdateUser] FOREIGN KEY ([UPDATED_BY_USER_ID]) REFERENCES [dbo].[PdtsUser] ([USER_ID])
);

