CREATE TABLE [dbo].[ProviderHostToPDTSLinkHistory] (
    [PROVIDER_LINK_ID]   INT         IDENTITY (1, 1) NOT NULL,
    [HOST_COID]          VARCHAR (5) NOT NULL,
    [HOST_PROVIDER_ID]   INT         NOT NULL,
    [PDTS_PROVIDER_ID]   INT         NOT NULL,
    [CREATE_DATE]        DATETIME    CONSTRAINT [DF_PROVIDER_HOST_TO_PDTS_LINK_HISTORY_CREATE_DATE] DEFAULT (getdate()) NOT NULL,
    [CREATED_BY_USER_ID] INT         NOT NULL,
    CONSTRAINT [PK_PROVIDER_HOST_TO_PDTS_LINK_HISTORY] PRIMARY KEY CLUSTERED ([PROVIDER_LINK_ID] ASC),
    CONSTRAINT [FK_PROVIDER_HOST_TO_PDTS_LINK_HISTORY_PdtsUser] FOREIGN KEY ([CREATED_BY_USER_ID]) REFERENCES [dbo].[PdtsUser] ([USER_ID]),
    CONSTRAINT [FK_PROVIDER_HOST_TO_PDTS_LINK_HISTORY_Provider] FOREIGN KEY ([PDTS_PROVIDER_ID]) REFERENCES [dbo].[Provider] ([PDTS_PROVIDER_ID]) ON DELETE CASCADE
);

