CREATE TABLE [dbo].[Provider] (
    [PDTS_PROVIDER_ID]                     INT            IDENTITY (1, 1) NOT NULL,
    [PROVIDER_ID]                          INT            NOT NULL,
    [COID]                                 VARCHAR (5)    NOT NULL,
    [LAST_NAME]                            VARCHAR (50)   NOT NULL,
    [FIRST_NAME]                           VARCHAR (50)   NULL,
    [MIDDLE_NAME]                          VARCHAR (50)   NULL,
    [FULL_NAME]                            VARCHAR (150)  NOT NULL,
    [DOB]                                  DATETIME       NULL,
    [SPECIALTY_ID]                         INT            NULL,
    [START_DATE]                           DATETIME       NULL,
    [LEFT_DATE]                            DATETIME       NULL,
    [PHYSICIAN_REASON_ID]                  INT            CONSTRAINT [DF_Provider_PHYSICIAN_REASON_ID] DEFAULT ((11)) NULL,
    [ACTIVE_FOR_ADMITS]                    BIT            CONSTRAINT [DF_Provider_ACTIVE_FOR_ADMITS] DEFAULT ((0)) NOT NULL,
    [ACTIVE_FOR_SURGERIES]                 BIT            CONSTRAINT [DF_Provider_ACTIVE_FOR_SURGERIES] DEFAULT ((0)) NOT NULL,
    [HOSPITALIST]                          BIT            CONSTRAINT [DF_Provider_HOSPITALIST] DEFAULT ((0)) NOT NULL,
    [LOCUM]                                BIT            CONSTRAINT [DF_Provider_LOCUM] DEFAULT ((0)) NOT NULL,
    [ADMITS_TO_HOSPITALIST]                BIT            CONSTRAINT [DF_Provider_FACILTIES_HOSPITAL_PROGRAM] DEFAULT ((0)) NOT NULL,
    [INDEPENDENT]                          BIT            CONSTRAINT [DF_Provider_INDEPENDENT] DEFAULT ((0)) NOT NULL,
    [EMPLOYED]                             BIT            CONSTRAINT [DF_Provider_EMPLOYED] DEFAULT ((0)) NOT NULL,
    [REVENUE_GUARANTEE]                    BIT            CONSTRAINT [DF_Provider_REVENUE] DEFAULT ((0)) NOT NULL,
    [BUDGET_PROVIDER_ID]                   INT            NULL,
    [EMPLOYEE_PHYSICIAN_COID]              VARCHAR (5)    NULL,
    [STARTING_MONTH]                       TINYINT        CONSTRAINT [DF_Provider_STARTING_MONTH] DEFAULT ((1)) NOT NULL,
    [PROVIDER_POSITION_STATUS_ID]          INT            CONSTRAINT [DF_Provider_BUDGET_TYPE_ID] DEFAULT ((1)) NULL,
    [CREATE_DATE]                          DATETIME       CONSTRAINT [DF_Provider_CREATE_DATE] DEFAULT (getdate()) NOT NULL,
    [CREATED_BY_USER_ID]                   INT            NOT NULL,
    [UPDATE_DATE]                          DATETIME       NULL,
    [UPDATED_BY_USER_ID]                   INT            NULL,
    [OTHER_REASON_TEXT]                    VARCHAR (500)  NULL,
    [RECRUITING]                           BIT            NULL,
    [PROVIDER_VOLUME_STATUS_ID]            INT            NULL,
    [PROVIDER_CONTRACT_TYPE_ID]            INT            CONSTRAINT [DF_Provider_PROVIDER_CONTRACT_TYPE_ID] DEFAULT ((4)) NOT NULL,
    [APPROVED_FOR_SCORECARD]               BIT            CONSTRAINT [DF_Provider_APPROVED_FOR_SCORECARD] DEFAULT ((0)) NOT NULL,
    [PHYSICIAN_GROUP]                      VARCHAR (50)   NULL,
    [SIGNED_DATE]                          DATETIME       NULL,
    [PROJECTED_START_DATE]                 DATETIME       NULL,
    [ON_HOLD]                              BIT            CONSTRAINT [DF_Provider_ON_HOLD] DEFAULT ((0)) NOT NULL,
    [BUDGETED_START_DATE]                  DATETIME       NULL,
    [DIVISION_PRIORITY]                    BIT            CONSTRAINT [DF_Provider_DIVISION_PRIORITY] DEFAULT ((0)) NOT NULL,
    [WATCH_LIST]                           BIT            CONSTRAINT [DF_Provider_WATCH_LIST] DEFAULT ((0)) NOT NULL,
    [PROVIDER_RECRUITMENT_STATUS_ID]       INT            NULL,
    [PROVIDER_TITLE_ID]                    INT            NULL,
    [NPI]                                  BIGINT         NULL,
    [SSN]                                  VARCHAR (11)   NULL,
    [MEDICARE]                             VARCHAR (40)   NULL,
    [MEDICAID]                             VARCHAR (40)   NULL,
    [BLUECROSS]                            VARCHAR (40)   NULL,
    [PROVIDER_SENIOR_DIRECTOR_ID]          INT            NULL,
    [PROVIDER_REGIONAL_DIRECTOR_ID]        INT            NULL,
    [PROVIDER_VP_PHYSICIAN_SERVICES_ID]    INT            NULL,
    [PROVIDER_DEPT_ID]                     INT            NULL,
    [PROVIDER_OVERHEAD_DEPT_ID]            INT            NULL,
    [NURSE_DEPT_ID]                        INT            NULL,
    [EMPLOYEE_PHYSICIAN_COID_NAME]         VARCHAR (50)   NULL,
    [GROUP_NPI]                            BIGINT         NULL,
    [ECW_ID]                               BIGINT         NULL,
    [CLINIC_DEPT_ID]                       INT            NULL,
    [ACTIVE]                               BIT            CONSTRAINT [DF_Provider_ACTIVE] DEFAULT ((1)) NOT NULL,
    [PROVIDER_RECRUITMENT_STATUS_DATE]     DATETIME       NULL,
    [MATERIAL_DOC]                         BIT            NULL,
    [MATERIAL_PHYSICIAN_REASON_ID]         INT            NULL,
    [COURTESY]                             BIT            CONSTRAINT [DF_Provider_COURTESY] DEFAULT ((0)) NOT NULL,
    [PROVIDER_AFFILIATION_ID]              INT            NULL,
    [FTE_ASSESSMENT]                       DECIMAL (2, 1) CONSTRAINT [DF_Provider_FTE_ASSESSMENT] DEFAULT ((0.0)) NULL,
    [PRIMARY_CARE_COMMUNITY_ACCEPTANCE_ID] INT            NULL,
    [PRIMARY_CARE_OTHER_RISK_ID]           INT            NULL,
    [PRIMARY_CARE_PRACTICE_REVENUE_ID]     INT            NULL,
    [PRIMARY_CARE_YEARS_IN_PRACTICE_ID]    INT            NULL,
    [RISK_SCORE]                           DECIMAL (2, 1) NULL,
    [RESPONSIBLE_PDTS_PROVIDER_ID]         INT            NULL,
    [EMAIL_ADDRESS]                        VARCHAR (50)   NULL,
    [DEA_NUMBER]                           VARCHAR (20)   NULL,
    [PRIMARY_ADDRESS_LINE1]                VARCHAR (50)   NULL,
    [PRIMARY_ADDRESS_LINE2]                VARCHAR (50)   NULL,
    [PRIMARY_ADDRESS_CITY]                 VARCHAR (50)   NULL,
    [PRIMARY_ADDRESS_STATE_ID]             INT            NULL,
    [PRIMARY_ADDRESS_ZIP]                  VARCHAR (9)    NULL,
    [PRIMARY_PHONE_NUMBER]                 VARCHAR (10)   NULL,
    [PROVIDER_AL_CODE_ID]                  INT            NULL,
    [SATISFACTION_SURVEY_PASSWORD]         VARCHAR (50)   NULL,
    [INCLUDE_IN_SAT_SURVEY]                BIT            CONSTRAINT [DF_Provider_INCLUDE_IN_SAT_SURVEY] DEFAULT ((0)) NOT NULL,
    [GENDER]                               CHAR (1)       NULL,
    [PROVIDER_TYPE_ID]                     INT            NULL,
    [SATISFACTION_SURVEY_MATCH_ID]         VARCHAR (50)   NULL,
    [PROVIDER_STAFF_STATUS_ID]             INT            NULL,
    [PROVIDER_DIRECTOR_ID]                 INT            NULL,
    [SRC_ID]                               INT            NULL,
    [SUM_NUMBER]                           INT            NULL,
    [PROVIDER_COUNT]                       INT            NULL,
    [JOINING_AN_EXISTING_PRACTICE]         BIT            CONSTRAINT [DF_Provider_JOINING_AN_EXISTING_PRACTICE] DEFAULT ((0)) NOT NULL,
    [REPLACING_AN_EXISTING_PROVIDER]       BIT            CONSTRAINT [DF_Provider_REPLACING_AN_EXISTING_PROVIDER] DEFAULT ((0)) NOT NULL,
    [PROVIDER_BEING_REPLACED]              VARCHAR (100)  NULL,
    [PRIOR_MALPRACTICE_COVERAGE_AMOUNT]    MONEY          NULL,
    [PRIOR_MALPRACTICE_COVERAGE_CARRIER]   VARCHAR (100)  NULL,
    [BUDGETED]                             BIT            CONSTRAINT [DF_Provider_BUDGETED] DEFAULT ((0)) NOT NULL,
    [NPPES_LOGIN]                          VARCHAR (50)   NULL,
    [NPPES_PASSWORD]                       VARCHAR (50)   NULL,
    [PROVIDER_LINE_OF_BUSINESS_ID]         INT            NULL,
    [EMPLOYED_PROVIDER_STATUS_ID]          INT            NULL,
    [SPECIALTY_TYPE_ID]                    INT            NULL,
    [PROVIDER_BILL_TYPE_ID]                INT            NULL,
    CONSTRAINT [PK_Provider_1] PRIMARY KEY CLUSTERED ([PDTS_PROVIDER_ID] ASC),
    CONSTRAINT [FK_Provider_EMPLOYED_PROVIDER_STATUS] FOREIGN KEY ([EMPLOYED_PROVIDER_STATUS_ID]) REFERENCES [dbo].[EMPLOYED_PROVIDER_STATUS] ([EMPLOYED_PROVIDER_STATUS_ID]),
    CONSTRAINT [FK_Provider_Material_Physician_Reason] FOREIGN KEY ([MATERIAL_PHYSICIAN_REASON_ID]) REFERENCES [dbo].[Material_Physician_Reason] ([material_physician_reason_id]),
    CONSTRAINT [FK_Provider_PRIMARY_CARE_COMMUNITY_ACCEPTANCE] FOREIGN KEY ([PRIMARY_CARE_COMMUNITY_ACCEPTANCE_ID]) REFERENCES [dbo].[PRIMARY_CARE_COMMUNITY_ACCEPTANCE] ([PRIMARY_CARE_COMMUNITY_ACCEPTANCE_ID]),
    CONSTRAINT [FK_Provider_PRIMARY_CARE_OTHER_RISK] FOREIGN KEY ([PRIMARY_CARE_OTHER_RISK_ID]) REFERENCES [dbo].[PRIMARY_CARE_OTHER_RISK] ([PRIMARY_CARE_OTHER_RISK_ID]),
    CONSTRAINT [FK_Provider_PRIMARY_CARE_PRACTICE_REVENUE] FOREIGN KEY ([PRIMARY_CARE_PRACTICE_REVENUE_ID]) REFERENCES [dbo].[PRIMARY_CARE_PRACTICE_REVENUE] ([PRIMARY_CARE_PRACTICE_REVENUE_ID]),
    CONSTRAINT [FK_Provider_PRIMARY_CARE_YEARS_IN_PRACTICE] FOREIGN KEY ([PRIMARY_CARE_YEARS_IN_PRACTICE_ID]) REFERENCES [dbo].[PRIMARY_CARE_YEARS_IN_PRACTICE] ([PRIMARY_CARE_YEARS_IN_PRACTICE_ID]),
    CONSTRAINT [FK_Provider_Provider] FOREIGN KEY ([RESPONSIBLE_PDTS_PROVIDER_ID]) REFERENCES [dbo].[Provider] ([PDTS_PROVIDER_ID]),
    CONSTRAINT [FK_Provider_PROVIDER_AFFILIATION] FOREIGN KEY ([PROVIDER_AFFILIATION_ID]) REFERENCES [dbo].[PROVIDER_AFFILIATION] ([PROVIDER_AFFILIATION_ID]),
    CONSTRAINT [FK_Provider_PROVIDER_AL_CODE] FOREIGN KEY ([PROVIDER_AL_CODE_ID]) REFERENCES [dbo].[PROVIDER_AL_CODE] ([PROVIDER_AL_CODE_ID]),
    CONSTRAINT [FK_Provider_PROVIDER_BILL_TYPE] FOREIGN KEY ([PROVIDER_BILL_TYPE_ID]) REFERENCES [dbo].[PROVIDER_BILL_TYPE] ([PROVIDER_BILL_TYPE_ID]),
    CONSTRAINT [FK_Provider_PROVIDER_DIRECTOR] FOREIGN KEY ([PROVIDER_DIRECTOR_ID]) REFERENCES [dbo].[PROVIDER_DIRECTOR] ([PROVIDER_DIRECTOR_ID]),
    CONSTRAINT [FK_Provider_PROVIDER_LINE_OF_BUSINESS] FOREIGN KEY ([PROVIDER_LINE_OF_BUSINESS_ID]) REFERENCES [dbo].[PROVIDER_LINE_OF_BUSINESS] ([PROVIDER_LINE_OF_BUSINESS_ID]),
    CONSTRAINT [FK_Provider_PROVIDER_STAFF_STATUS] FOREIGN KEY ([PROVIDER_STAFF_STATUS_ID]) REFERENCES [dbo].[PROVIDER_STAFF_STATUS] ([PROVIDER_STAFF_STATUS_ID]),
    CONSTRAINT [FK_Provider_PROVIDER_TYPE] FOREIGN KEY ([PROVIDER_TYPE_ID]) REFERENCES [dbo].[PROVIDER_TYPE] ([PROVIDER_TYPE_ID]),
    CONSTRAINT [FK_Provider_SPECIALTY_TYPE] FOREIGN KEY ([SPECIALTY_TYPE_ID]) REFERENCES [dbo].[SPECIALTY_TYPE] ([SPECIALTY_TYPE_ID]),
    CONSTRAINT [FK_Provider_State] FOREIGN KEY ([PRIMARY_ADDRESS_STATE_ID]) REFERENCES [dbo].[State] ([STATE_ID])
);

