CREATE TABLE [dbo].[PROVIDER_BILL_TYPE] (
    [PROVIDER_BILL_TYPE_ID] INT          IDENTITY (1, 1) NOT NULL,
    [NAME]                  VARCHAR (50) NULL,
    CONSTRAINT [PK_PROVIDER_BILL_TYPE] PRIMARY KEY CLUSTERED ([PROVIDER_BILL_TYPE_ID] ASC)
);

