CREATE TABLE [dbo].[PROVIDER_AUDITOR] (
    [PROVIDER_AUDITOR_ID] INT          IDENTITY (1, 1) NOT NULL,
    [LAST_NAME]           VARCHAR (50) NOT NULL,
    [FIRST_NAME]          VARCHAR (50) NOT NULL,
    [CREATE_DATE]         DATETIME     CONSTRAINT [DF_PROVIDER_AUDITOR_CREATE_DATE] DEFAULT (getdate()) NOT NULL,
    [CREATED_BY_USER_ID]  INT          NOT NULL,
    [UPDATE_DATE]         DATETIME     NULL,
    [UPDATED_BY_USER_ID]  INT          NULL,
    CONSTRAINT [PK_PROVIDER_AUDITOR] PRIMARY KEY CLUSTERED ([PROVIDER_AUDITOR_ID] ASC),
    CONSTRAINT [FK_PROVIDER_AUDITOR_CreateUser] FOREIGN KEY ([CREATED_BY_USER_ID]) REFERENCES [dbo].[PdtsUser] ([USER_ID]),
    CONSTRAINT [FK_PROVIDER_AUDITOR_UpdateUser] FOREIGN KEY ([UPDATED_BY_USER_ID]) REFERENCES [dbo].[PdtsUser] ([USER_ID])
);

