CREATE TABLE [dbo].[PROVIDER_DIRECTOR] (
    [PROVIDER_DIRECTOR_ID]        INT      IDENTITY (1, 1) NOT NULL,
    [USER_ID]                     INT      NOT NULL,
    [PROVIDER_SENIOR_DIRECTOR_ID] INT      NOT NULL,
    [CREATED_BY_USER_ID]          INT      NOT NULL,
    [CREATE_DATE]                 DATETIME CONSTRAINT [DF_PROVIDER_DIRECTOR_CREATE_DATE] DEFAULT (getdate()) NOT NULL,
    [UPDATED_BY_USER_ID]          INT      NULL,
    [UPDATE_DATE]                 DATETIME NULL,
    CONSTRAINT [PK_PROVIDER_DIRECTOR] PRIMARY KEY CLUSTERED ([PROVIDER_DIRECTOR_ID] ASC),
    CONSTRAINT [FK_PROVIDER_DIRECTOR_PdtsUser] FOREIGN KEY ([CREATED_BY_USER_ID]) REFERENCES [dbo].[PdtsUser] ([USER_ID]),
    CONSTRAINT [FK_PROVIDER_DIRECTOR_PdtsUser1] FOREIGN KEY ([UPDATED_BY_USER_ID]) REFERENCES [dbo].[PdtsUser] ([USER_ID]),
    CONSTRAINT [FK_PROVIDER_DIRECTOR_PdtsUser2] FOREIGN KEY ([USER_ID]) REFERENCES [dbo].[PdtsUser] ([USER_ID]),
    CONSTRAINT [FK_PROVIDER_DIRECTOR_ProviderSeniorDirector] FOREIGN KEY ([PROVIDER_SENIOR_DIRECTOR_ID]) REFERENCES [dbo].[ProviderSeniorDirector] ([PROVIDER_SENIOR_DIRECTOR_ID])
);

