CREATE TABLE [dbo].[PROVIDER_REQUIREMENT] (
    [PROVIDER_REQUIREMENT_ID]      INT      IDENTITY (1, 1) NOT NULL,
    [PDTS_PROVIDER_ID]             INT      NOT NULL,
    [YEARS_EXPERIENCE_REQUIRED_ID] INT      NULL,
    [BOARD_CERTIFICATION_REQUIRED] BIT      CONSTRAINT [DF_PROVIDER_REQUIREMENT_BOARD_CERTIFICATION_REQUIRED] DEFAULT ((0)) NOT NULL,
    [BOARD_ELIGIBLE]               BIT      CONSTRAINT [DF_PROVIDER_REQUIREMENT_BOARD_ELIGIBLE] DEFAULT ((0)) NOT NULL,
    [VISA_J1_CANDIDATE]            BIT      CONSTRAINT [DF_PROVIDER_REQUIREMENT_VISA_J1_CANDIDATE] DEFAULT ((0)) NOT NULL,
    [VISA_H1B_CANDIDATE]           BIT      CONSTRAINT [DF_PROVIDER_REQUIREMENT_VISA_H1B_CANDIDATE] DEFAULT ((0)) NOT NULL,
    [CREATE_DATE]                  DATETIME CONSTRAINT [DF_PROVIDER_REQUIREMENT_CREATE_DATE] DEFAULT (getdate()) NOT NULL,
    [CREATED_BY_USER_ID]           INT      NOT NULL,
    [UPDATE_DATE]                  DATETIME NULL,
    [UPDATED_BY_USER_ID]           INT      NULL,
    CONSTRAINT [PK_PROVIDER_REQUIREMENT] PRIMARY KEY CLUSTERED ([PROVIDER_REQUIREMENT_ID] ASC),
    CONSTRAINT [FK_PROVIDER_REQUIREMENT_CreateUser] FOREIGN KEY ([CREATED_BY_USER_ID]) REFERENCES [dbo].[PdtsUser] ([USER_ID]),
    CONSTRAINT [FK_PROVIDER_REQUIREMENT_Provider] FOREIGN KEY ([PDTS_PROVIDER_ID]) REFERENCES [dbo].[Provider] ([PDTS_PROVIDER_ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_PROVIDER_REQUIREMENT_PROVIDER_YEARS_EXPERIENCE_REQUIRED] FOREIGN KEY ([YEARS_EXPERIENCE_REQUIRED_ID]) REFERENCES [dbo].[PROVIDER_YEARS_EXPERIENCE_REQUIRED] ([YEARS_EXPERIENCE_REQUIRED_ID]),
    CONSTRAINT [FK_PROVIDER_REQUIREMENT_UpdateUser] FOREIGN KEY ([UPDATED_BY_USER_ID]) REFERENCES [dbo].[PdtsUser] ([USER_ID])
);

