CREATE TABLE [dbo].[QRM_MEASURE] (
    [QRM_MEASURE_ID]         INT         IDENTITY (1, 1) NOT NULL,
    [COID]                   VARCHAR (5) NOT NULL,
    [QRM_MEASURE_TYPE_ID]    INT         NOT NULL,
    [REPORTING_PERIOD_MONTH] INT         NOT NULL,
    [REPORTING_PERIOD_YEAR]  INT         NOT NULL,
    [VALUE]                  INT         NOT NULL,
    [CREATE_DATE]            DATETIME    CONSTRAINT [DF_QRM_MEASURE_CREATE_DATE] DEFAULT (getdate()) NOT NULL,
    [CREATED_BY_USER_ID]     INT         NOT NULL,
    [UPDATE_DATE]            DATETIME    NULL,
    [UPDATED_BY_USER_ID]     INT         NULL,
    [REPORTING_DATE]         DATETIME    NOT NULL,
    CONSTRAINT [PK_QRM_MEASURE] PRIMARY KEY CLUSTERED ([QRM_MEASURE_ID] ASC),
    CONSTRAINT [FK_QRM_MEASURE_CreateUser] FOREIGN KEY ([CREATED_BY_USER_ID]) REFERENCES [dbo].[PdtsUser] ([USER_ID]),
    CONSTRAINT [FK_QRM_MEASURE_Facility] FOREIGN KEY ([COID]) REFERENCES [dbo].[Facility] ([COID]),
    CONSTRAINT [FK_QRM_MEASURE_QRM_MEASURE] FOREIGN KEY ([QRM_MEASURE_TYPE_ID]) REFERENCES [dbo].[QRM_MEASURE_TYPE] ([QRM_MEASURE_TYPE_ID]),
    CONSTRAINT [FK_QRM_MEASURE_UpdateUser] FOREIGN KEY ([UPDATED_BY_USER_ID]) REFERENCES [dbo].[PdtsUser] ([USER_ID])
);

