CREATE TABLE [dbo].[QRM_MEASURE_TYPE_GROUP] (
    [QRM_MEASURE_TYPE_GROUP_ID] INT          IDENTITY (1, 1) NOT NULL,
    [NAME]                      VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_QRM_MEASURE_TYPE_GROUP] PRIMARY KEY CLUSTERED ([QRM_MEASURE_TYPE_GROUP_ID] ASC)
);

