CREATE TABLE [dbo].[QRM_MEASURE_NOTE] (
    [QRM_MEASURE_NOTE_ID] INT            IDENTITY (1, 1) NOT NULL,
    [COID]                VARCHAR (5)    NOT NULL,
    [NOTE_TYPE_ID]        INT            NOT NULL,
    [NOTE]                VARCHAR (2000) NOT NULL,
    [CREATED_BY_USER_ID]  INT            NOT NULL,
    [CREATE_DATE]         DATETIME       CONSTRAINT [DF_QRM_MEASURE_NOTE_CREATE_DATE] DEFAULT (getdate()) NOT NULL,
    [UPDATED_BY_USER_ID]  INT            NULL,
    [UPDATE_DATE]         DATETIME       NULL,
    [REPORTING_PERIOD]    DATETIME       NOT NULL,
    CONSTRAINT [PK_QRM_MEASURE_NOTE] PRIMARY KEY CLUSTERED ([QRM_MEASURE_NOTE_ID] ASC),
    CONSTRAINT [FK_QRM_MEASURE_NOTE_CreateUser] FOREIGN KEY ([CREATED_BY_USER_ID]) REFERENCES [dbo].[PdtsUser] ([USER_ID]),
    CONSTRAINT [FK_QRM_MEASURE_NOTE_Facility] FOREIGN KEY ([COID]) REFERENCES [dbo].[Facility] ([COID]),
    CONSTRAINT [FK_QRM_MEASURE_NOTE_Note_Type] FOREIGN KEY ([NOTE_TYPE_ID]) REFERENCES [dbo].[Note_Type] ([NOTE_TYPE_ID]),
    CONSTRAINT [FK_QRM_MEASURE_NOTE_UpdateUser] FOREIGN KEY ([UPDATED_BY_USER_ID]) REFERENCES [dbo].[PdtsUser] ([USER_ID])
);

