CREATE TABLE [dbo].[QRM_MEASURE_TYPE] (
    [QRM_MEASURE_TYPE_ID]           INT           IDENTITY (1, 1) NOT NULL,
    [NAME]                          VARCHAR (250) NOT NULL,
    [CREATE_DATE]                   DATETIME      CONSTRAINT [DF_QRM_TYPE_CREATE_DATE] DEFAULT (getdate()) NOT NULL,
    [CREATED_BY_USER_ID]            INT           NOT NULL,
    [UPDATE_DATE]                   DATETIME      NULL,
    [UPDATED_BY_USER_ID]            INT           NULL,
    [REPORT_SORT_ORDER]             INT           NULL,
    [SUMMARIZED_STAT_DEFINITION_ID] INT           NULL,
    [QRM_MEASURE_TYPE_GROUP_ID]     INT           NULL,
    CONSTRAINT [PK_QRM_TYPE] PRIMARY KEY CLUSTERED ([QRM_MEASURE_TYPE_ID] ASC),
    CONSTRAINT [FK_QRM_MEASURE_TYPE_QRM_MEASURE_TYPE_GROUP] FOREIGN KEY ([QRM_MEASURE_TYPE_GROUP_ID]) REFERENCES [dbo].[QRM_MEASURE_TYPE_GROUP] ([QRM_MEASURE_TYPE_GROUP_ID]),
    CONSTRAINT [FK_QRM_TYPE_CreateUser] FOREIGN KEY ([CREATED_BY_USER_ID]) REFERENCES [dbo].[PdtsUser] ([USER_ID]),
    CONSTRAINT [FK_QRM_TYPE_UpdateUser] FOREIGN KEY ([UPDATED_BY_USER_ID]) REFERENCES [dbo].[PdtsUser] ([USER_ID])
);

