CREATE TABLE [dbo].[SHEATH_SIZE] (
    [SHEATH_SIZE_ID] INT          IDENTITY (1, 1) NOT NULL,
    [NAME]           VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_SHEATH_SIZE] PRIMARY KEY CLUSTERED ([SHEATH_SIZE_ID] ASC)
);

