CREATE TABLE [dbo].[SPECIALTY_TYPE] (
    [SPECIALTY_TYPE_ID] INT          IDENTITY (1, 1) NOT NULL,
    [NAME]              VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_SPECIALTY_TYPE] PRIMARY KEY CLUSTERED ([SPECIALTY_TYPE_ID] ASC)
);

