CREATE TABLE [dbo].[Strategy] (
    [STRATEGY_ID]                            INT            IDENTITY (1, 1) NOT NULL,
    [COID]                                   VARCHAR (5)    NOT NULL,
    [NAME]                                   VARCHAR (1000) NOT NULL,
    [CATEGORY_ID]                            INT            NOT NULL,
    [GOAL_TYPE_ID]                           INT            NOT NULL,
    [MEASURABLE_RESULT_ID]                   INT            NULL,
    [OTHER_MEASURABLE_RESULT_TEXT]           VARCHAR (500)  NULL,
    [OTHER_MEASURABLE_RESULT_FREQUENCY_TEXT] VARCHAR (50)   NULL,
    [PRODUCT_LINE_ID]                        INT            NULL,
    [SPECIALTY_ID]                           INT            NULL,
    [CREATE_DATE]                            DATETIME       CONSTRAINT [DF_Strategy_CREATE_DATE] DEFAULT (getdate()) NOT NULL,
    [CREATED_BY_USER_ID]                     INT            NOT NULL,
    [UPDATE_DATE]                            DATETIME       NULL,
    [UPDATED_BY_USER_ID]                     INT            NULL,
    [START_DATE]                             DATETIME       NULL,
    [RESULTS]                                VARCHAR (1000) NULL,
    [TARGETED_COMPLETION_DATE]               VARCHAR (50)   NULL,
    [REPORTING_PERIOD_YEAR]                  INT            NULL,
    [REPORTING_PERIOD_MONTH]                 INT            NULL,
    [VOLUME_ID]                              INT            NULL,
    [STANDARD_STRATEGY_ID]                   INT            NULL,
    [STRATEGY_STATUS_ID]                     INT            CONSTRAINT [DF_Strategy_STRATEGY_STATUS_ID] DEFAULT ((1)) NOT NULL,
    [SORT_ORDER]                             INT            NULL,
    [PROJECT_OWNER]                          VARCHAR (100)  NULL,
    CONSTRAINT [PK_Strategy] PRIMARY KEY CLUSTERED ([STRATEGY_ID] ASC),
    CONSTRAINT [FK_Strategy_Facility] FOREIGN KEY ([COID]) REFERENCES [dbo].[Facility] ([COID]),
    CONSTRAINT [FK_Strategy_PdtsUser] FOREIGN KEY ([CREATED_BY_USER_ID]) REFERENCES [dbo].[PdtsUser] ([USER_ID]),
    CONSTRAINT [FK_Strategy_PdtsUser1] FOREIGN KEY ([UPDATED_BY_USER_ID]) REFERENCES [dbo].[PdtsUser] ([USER_ID]),
    CONSTRAINT [FK_Strategy_Specialty] FOREIGN KEY ([SPECIALTY_ID]) REFERENCES [dbo].[Specialty] ([SPECIALTY_ID]),
    CONSTRAINT [FK_Strategy_StrategyCategory] FOREIGN KEY ([CATEGORY_ID]) REFERENCES [dbo].[StrategyCategory] ([CATEGORY_ID]),
    CONSTRAINT [FK_Strategy_StrategyGoalType] FOREIGN KEY ([GOAL_TYPE_ID]) REFERENCES [dbo].[StrategyGoalType] ([GOAL_TYPE_ID]),
    CONSTRAINT [FK_Strategy_StrategyMeasurableResult] FOREIGN KEY ([MEASURABLE_RESULT_ID]) REFERENCES [dbo].[StrategyMeasurableResult] ([MEASURABLE_RESULT_ID]),
    CONSTRAINT [FK_Strategy_StrategyProductLine] FOREIGN KEY ([PRODUCT_LINE_ID]) REFERENCES [dbo].[StrategyProductLine] ([PRODUCT_LINE_ID]),
    CONSTRAINT [FK_Strategy_StrategyStandard] FOREIGN KEY ([STANDARD_STRATEGY_ID]) REFERENCES [dbo].[StrategyStandard] ([STANDARD_STRATEGY_ID]),
    CONSTRAINT [FK_Strategy_StrategyStatus] FOREIGN KEY ([STRATEGY_STATUS_ID]) REFERENCES [dbo].[StrategyStatus] ([STRATEGY_STATUS_ID]),
    CONSTRAINT [FK_Strategy_VolumeCommentType] FOREIGN KEY ([VOLUME_ID]) REFERENCES [dbo].[VolumeCommentType] ([VOLUME_ID])
);

