CREATE TABLE [dbo].[SURVEY_CYCLE] (
    [SURVEY_CYCLE_ID] INT           IDENTITY (1, 1) NOT NULL,
    [CYCLE_ID]        NVARCHAR (50) NOT NULL,
    [COID]            VARCHAR (5)   NOT NULL,
    CONSTRAINT [PK_SURVEY_CYCLE] PRIMARY KEY CLUSTERED ([SURVEY_CYCLE_ID] ASC)
);

