CREATE TABLE [dbo].[SURVEY_ANSWER] (
    [SURVEY_ANSWER_ID] INT           IDENTITY (1, 1) NOT NULL,
    [ANSWER_VALUE]     VARCHAR (10)  NOT NULL,
    [ANSWER]           VARCHAR (100) NOT NULL,
    CONSTRAINT [PK_SURVEY_ANSWER] PRIMARY KEY CLUSTERED ([SURVEY_ANSWER_ID] ASC)
);

