CREATE TABLE [dbo].[SURVEY_QUESTION] (
    [QUESTION_ID]              INT           IDENTITY (1, 1) NOT NULL,
    [SURVEY_QUESTION_TEXT]     VARCHAR (500) NOT NULL,
    [CATEGORY_ID]              INT           NOT NULL,
    [DATA_COL]                 VARCHAR (50)  NOT NULL,
    [REPORT_PRESENTATION_TEXT] VARCHAR (500) NULL,
    [TOP_BOX_ANSWERS]          VARCHAR (50)  NULL,
    CONSTRAINT [PK_SURVEY_QUESTION] PRIMARY KEY CLUSTERED ([QUESTION_ID] ASC),
    CONSTRAINT [FK_SURVEY_QUESTION_SURVEY_CATEGORY] FOREIGN KEY ([CATEGORY_ID]) REFERENCES [dbo].[SURVEY_CATEGORY] ([CATEGORY_ID])
);

