CREATE TABLE [dbo].[TBUT_ACCOUNT_RANGE] (
    [TUBT_ACCOUNT_RANGE_ID] INT          IDENTITY (1, 1) NOT NULL,
    [COID]                  VARCHAR (5)  NOT NULL,
    [BEGIN_RANGE]           VARCHAR (50) NOT NULL,
    [END_RANGE]             VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_TBUT_ACCOUNT_RANGE] PRIMARY KEY CLUSTERED ([TUBT_ACCOUNT_RANGE_ID] ASC),
    CONSTRAINT [FK_TBUT_ACCOUNT_RANGE_Facility] FOREIGN KEY ([COID]) REFERENCES [dbo].[Facility] ([COID])
);

