CREATE PROCEDURE [dbo].[sp_report_PI_TeamMinutesReport]
	(
		@coid VARCHAR(5)
	)
AS
BEGIN
	SET NOCOUNT ON;

	SELECT a.performance_improvement_idea_id, 
		a.idea, b.NAME AS team, 
		c.name AS quadrant,
		d.name AS idea_type,
		e.name AS approval_status,
		a.TOTAL_PROJECTED_SAVINGS,
		a.ASSIGNED_TEAM_MEMBER,
		a.STEERING_COMMITTEE,
		f.MINUTES_DATE,
		f.minutes,
		g.NAME AS facility
	FROM dbo.PERFORMANCE_IMPROVEMENT_IDEA a WITH (NOLOCK)
		JOIN dbo.PERFORMANCE_IMPROVEMENT_TEAM b with (NOLOCK)
			ON b.PERFORMANCE_IMPROVEMENT_TEAM_ID = a.PERFORMANCE_IMPROVEMENT_TEAM_ID

		LEFT JOIN dbo.PERFORMANCE_IMPROVEMENT_PAYOFF_QUADRANT c with (NOLOCK)
			ON c.PERFORMANCE_IMPROVEMENT_PAYOFF_QUADRANT_ID = a.PERFORMANCE_IMPROVEMENT_PAYOFF_QUADRANT_ID

		LEFT JOIN dbo.PERFORMANCE_IMPROVEMENT_IDEA_TYPE d with (NOLOCK)
			ON d.PERFORMANCE_IMPROVEMENT_IDEA_TYPE_ID = a.PERFORMANCE_IMPROVEMENT_IDEA_TYPE_ID

		LEFT join dbo.PERFORMANCE_IMPROVEMENT_IDEA_STATUS e WITH (NOLOCK)
			ON e.PERFOMANCE_IMPROVEMENT_IDEA_STATUS_ID = a.PERFORMANCE_IMPROVEMENT_IDEA_STATUS_ID

		LEFT JOIN dbo.PERFORMANCE_IMPROVEMENT_MINUTES f WITH (NOLOCK)
			ON f.PERFORMANCE_IMPROVEMENT_IDEA_ID = a.PERFORMANCE_IMPROVEMENT_IDEA_ID

		JOIN Facility g WITH (NOLOCK)
			ON g.coid = a.coid
	WHERE a.coid = @coid
END

