
CREATE PROCEDURE [dbo].[sp_report_ED_Patient_Analysis_VisitsByLevel]
	(
		@coid VARCHAR(5),
		@year INT,
		@month int
	)
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @t TABLE
		(
			coid VARCHAR(5),
			cy_ed_visits INT DEFAULT 0,
			py_ed_visits INT DEFAULT 0,
			cytd_ed_visits INT DEFAULT 0,
			pytd_ed_visits INT DEFAULT 0,
			cy_no_level INT DEFAULT 0,
			cy_level1 INT DEFAULT 0,
			cy_level2 INT DEFAULT 0,
			cy_level3 INT DEFAULT 0,
			cy_level4 INT DEFAULT 0,
			cy_level5 INT DEFAULT 0,
			cy_critical_care INT DEFAULT 0,
			py_no_level INT DEFAULT 0,
			py_level1 INT DEFAULT 0,
			py_level2 INT DEFAULT 0,
			py_level3 INT DEFAULT 0,
			py_level4 INT DEFAULT 0,
			py_level5 INT DEFAULT 0,
			py_critical_care INT DEFAULT 0,
			cytd_no_level INT DEFAULT 0,
			cytd_level1 INT DEFAULT 0,
			cytd_level2 INT DEFAULT 0,
			cytd_level3 INT DEFAULT 0,
			cytd_level4 INT DEFAULT 0,
			cytd_level5 INT DEFAULT 0,
			cytd_critical_care INT DEFAULT 0,
			pytd_no_level INT DEFAULT 0,
			pytd_level1 INT DEFAULT 0,
			pytd_level2 INT DEFAULT 0,
			pytd_level3 INT DEFAULT 0,
			pytd_level4 INT DEFAULT 0,
			pytd_level5 INT DEFAULT 0,
			pytd_critical_care int DEFAULT 0
		)

	INSERT INTO @t (coid)
	VALUES (@coid);

	UPDATE @t
	SET cy_no_level =
		(
			SELECT COUNT(DISTINCT a.er_data_id)
			FROM dbo.ER_MONTHLY_DATA a WITH (NOLOCK)
				JOIN dbo.ER_MONTHLY_DATA_DETAIL b WITH (NOLOCK)
					ON a.ER_DATA_ID = b.ER_DATA_ID
						AND ((b.CHARGE_REV_CODE BETWEEN 450 AND 459) OR (b.CHARGE_REV_CODE BETWEEN 680 AND 689))
				LEFT JOIN dbo.ER_MONTHLY_DATA_DETAIL c WITH (NOLOCK)
					ON a.ER_DATA_ID = c.ER_DATA_ID
						AND c.CHARGE_HCPCS_PROC IN ('099281', '099282', '099283', '099284', '099285', '099291', '099292')
			WHERE a.coid = @coid
				AND a.YEAR_OF_DISCHARGE_DATE = @year
				AND a.MONTH_OF_DISCHARGE_DATE = @month
				AND c.ER_DATA_ID IS null
		)

	UPDATE @t
	SET cy_level1 =
		(
			SELECT COUNT(DISTINCT a.er_data_id)
			FROM dbo.ER_MONTHLY_DATA a WITH (NOLOCK)
				JOIN dbo.ER_MONTHLY_DATA_DETAIL b WITH (NOLOCK)
					ON a.ER_DATA_ID = b.ER_DATA_ID
						AND ((b.CHARGE_REV_CODE BETWEEN 450 AND 459) OR (b.CHARGE_REV_CODE BETWEEN 680 AND 689))

				JOIN dbo.ER_MONTHLY_DATA_DETAIL c WITH (NOLOCK)
					ON a.ER_DATA_ID = c.ER_DATA_ID
						AND c.CHARGE_HCPCS_PROC = '099281'
			WHERE a.coid = @coid
				AND a.YEAR_OF_DISCHARGE_DATE = @year
				AND a.MONTH_OF_DISCHARGE_DATE = @month
		)

	UPDATE @t
	SET cy_level2 =
		(
			SELECT COUNT(DISTINCT a.er_data_id)
			FROM dbo.ER_MONTHLY_DATA a WITH (NOLOCK)
				JOIN dbo.ER_MONTHLY_DATA_DETAIL b WITH (NOLOCK)
					ON a.ER_DATA_ID = b.ER_DATA_ID
						AND ((b.CHARGE_REV_CODE BETWEEN 450 AND 459) OR (b.CHARGE_REV_CODE BETWEEN 680 AND 689))

				JOIN dbo.ER_MONTHLY_DATA_DETAIL c WITH (NOLOCK)
					ON a.ER_DATA_ID = c.ER_DATA_ID
						AND c.CHARGE_HCPCS_PROC = '099282'
			WHERE a.coid = @coid
				AND a.YEAR_OF_DISCHARGE_DATE = @year
				AND a.MONTH_OF_DISCHARGE_DATE = @month
		)

	UPDATE @t
	SET cy_level3 =
		(
			SELECT COUNT(DISTINCT a.er_data_id)
			FROM dbo.ER_MONTHLY_DATA a WITH (NOLOCK)
				JOIN dbo.ER_MONTHLY_DATA_DETAIL b WITH (NOLOCK)
					ON a.ER_DATA_ID = b.ER_DATA_ID
						AND ((b.CHARGE_REV_CODE BETWEEN 450 AND 459) OR (b.CHARGE_REV_CODE BETWEEN 680 AND 689))

				JOIN dbo.ER_MONTHLY_DATA_DETAIL c WITH (NOLOCK)
					ON a.ER_DATA_ID = c.ER_DATA_ID
						AND c.CHARGE_HCPCS_PROC = '099283'
			WHERE a.coid = @coid
				AND a.YEAR_OF_DISCHARGE_DATE = @year
				AND a.MONTH_OF_DISCHARGE_DATE = @month
		)

	UPDATE @t
	SET cy_level4 =
		(
			SELECT COUNT(DISTINCT a.er_data_id)
			FROM dbo.ER_MONTHLY_DATA a WITH (NOLOCK)
				JOIN dbo.ER_MONTHLY_DATA_DETAIL b WITH (NOLOCK)
					ON a.ER_DATA_ID = b.ER_DATA_ID
						AND ((b.CHARGE_REV_CODE BETWEEN 450 AND 459) OR (b.CHARGE_REV_CODE BETWEEN 680 AND 689))

				JOIN dbo.ER_MONTHLY_DATA_DETAIL c WITH (NOLOCK)
					ON a.ER_DATA_ID = c.ER_DATA_ID
						AND c.CHARGE_HCPCS_PROC = '099284'
			WHERE a.coid = @coid
				AND a.YEAR_OF_DISCHARGE_DATE = @year
				AND a.MONTH_OF_DISCHARGE_DATE = @month
		)

	UPDATE @t
	SET cy_level5 =
		(
			SELECT COUNT(DISTINCT a.er_data_id)
			FROM dbo.ER_MONTHLY_DATA a WITH (NOLOCK)
				JOIN dbo.ER_MONTHLY_DATA_DETAIL b WITH (NOLOCK)
					ON a.ER_DATA_ID = b.ER_DATA_ID
						AND ((b.CHARGE_REV_CODE BETWEEN 450 AND 459) OR (b.CHARGE_REV_CODE BETWEEN 680 AND 689))

				JOIN dbo.ER_MONTHLY_DATA_DETAIL c WITH (NOLOCK)
					ON a.ER_DATA_ID = c.ER_DATA_ID
						AND c.CHARGE_HCPCS_PROC = '099285'
			WHERE a.coid = @coid
				AND a.YEAR_OF_DISCHARGE_DATE = @year
				AND a.MONTH_OF_DISCHARGE_DATE = @month
		)

	UPDATE @t
	SET cy_critical_care =
		(
			SELECT COUNT(DISTINCT a.er_data_id)
			FROM dbo.ER_MONTHLY_DATA a WITH (NOLOCK)
				JOIN dbo.ER_MONTHLY_DATA_DETAIL b WITH (NOLOCK)
					ON a.ER_DATA_ID = b.ER_DATA_ID
						AND ((b.CHARGE_REV_CODE BETWEEN 450 AND 459) OR (b.CHARGE_REV_CODE BETWEEN 680 AND 689))

				JOIN dbo.ER_MONTHLY_DATA_DETAIL c WITH (NOLOCK)
					ON a.ER_DATA_ID = c.ER_DATA_ID
						AND c.CHARGE_HCPCS_PROC IN ('099291', '099292')
			WHERE a.coid = @coid
				AND a.YEAR_OF_DISCHARGE_DATE = @year
				AND a.MONTH_OF_DISCHARGE_DATE = @month
		)

	UPDATE @t
	SET py_no_level =
		(
			SELECT COUNT(DISTINCT a.er_data_id)
			FROM dbo.ER_MONTHLY_DATA a WITH (NOLOCK)
				JOIN dbo.ER_MONTHLY_DATA_DETAIL b WITH (NOLOCK)
					ON a.ER_DATA_ID = b.ER_DATA_ID
						AND ((b.CHARGE_REV_CODE BETWEEN 450 AND 459) OR (b.CHARGE_REV_CODE BETWEEN 680 AND 689))

				LEFT JOIN dbo.ER_MONTHLY_DATA_DETAIL c WITH (NOLOCK)
					ON a.ER_DATA_ID = c.ER_DATA_ID
						AND c.CHARGE_HCPCS_PROC IN ('099281', '099282', '099283', '099284', '099285', '099291', '099292')
			WHERE a.coid = @coid
				AND a.YEAR_OF_DISCHARGE_DATE = (@year - 1)
				AND a.MONTH_OF_DISCHARGE_DATE = @month
				AND c.ER_DATA_ID IS NULL
		)              
                
	UPDATE @t
	SET py_level1 =
		(
			SELECT COUNT(DISTINCT a.er_data_id)
			FROM dbo.ER_MONTHLY_DATA a WITH (NOLOCK)
				JOIN dbo.ER_MONTHLY_DATA_DETAIL b WITH (NOLOCK)
					ON a.ER_DATA_ID = b.ER_DATA_ID
						AND ((b.CHARGE_REV_CODE BETWEEN 450 AND 459) OR (b.CHARGE_REV_CODE BETWEEN 680 AND 689))

				JOIN dbo.ER_MONTHLY_DATA_DETAIL c WITH (NOLOCK)
					ON a.ER_DATA_ID = c.ER_DATA_ID
						AND c.CHARGE_HCPCS_PROC = '099281'
			WHERE a.coid = @coid
				AND a.YEAR_OF_DISCHARGE_DATE = (@year - 1)
				AND a.MONTH_OF_DISCHARGE_DATE = @month
		)

	UPDATE @t
	SET py_level2 =
		(
			SELECT COUNT(DISTINCT a.er_data_id)
			FROM dbo.ER_MONTHLY_DATA a WITH (NOLOCK)
				JOIN dbo.ER_MONTHLY_DATA_DETAIL b WITH (NOLOCK)
					ON a.ER_DATA_ID = b.ER_DATA_ID
						AND ((b.CHARGE_REV_CODE BETWEEN 450 AND 459) OR (b.CHARGE_REV_CODE BETWEEN 680 AND 689))

				JOIN dbo.ER_MONTHLY_DATA_DETAIL c WITH (NOLOCK)
					ON a.ER_DATA_ID = c.ER_DATA_ID
						AND c.CHARGE_HCPCS_PROC = '099282'
			WHERE a.coid = @coid
				AND a.YEAR_OF_DISCHARGE_DATE = (@year - 1)
				AND a.MONTH_OF_DISCHARGE_DATE = @month
		)

	UPDATE @t
	SET py_level3 =
		(
			SELECT COUNT(DISTINCT a.er_data_id)
			FROM dbo.ER_MONTHLY_DATA a WITH (NOLOCK)
				JOIN dbo.ER_MONTHLY_DATA_DETAIL b WITH (NOLOCK)
					ON a.ER_DATA_ID = b.ER_DATA_ID
						AND ((b.CHARGE_REV_CODE BETWEEN 450 AND 459) OR (b.CHARGE_REV_CODE BETWEEN 680 AND 689))

				JOIN dbo.ER_MONTHLY_DATA_DETAIL c WITH (NOLOCK)
					ON a.ER_DATA_ID = c.ER_DATA_ID
						AND c.CHARGE_HCPCS_PROC = '099283'
			WHERE a.coid = @coid
				AND a.YEAR_OF_DISCHARGE_DATE = (@year - 1)
				AND a.MONTH_OF_DISCHARGE_DATE = @month
		)

	UPDATE @t
	SET py_level4 =
		(
			SELECT COUNT(DISTINCT a.er_data_id)
			FROM dbo.ER_MONTHLY_DATA a WITH (NOLOCK)
				JOIN dbo.ER_MONTHLY_DATA_DETAIL b WITH (NOLOCK)
					ON a.ER_DATA_ID = b.ER_DATA_ID
						AND ((b.CHARGE_REV_CODE BETWEEN 450 AND 459) OR (b.CHARGE_REV_CODE BETWEEN 680 AND 689))

				JOIN dbo.ER_MONTHLY_DATA_DETAIL c WITH (NOLOCK)
					ON a.ER_DATA_ID = c.ER_DATA_ID
						AND c.CHARGE_HCPCS_PROC = '099284'
			WHERE a.coid = @coid
				AND a.YEAR_OF_DISCHARGE_DATE = (@year - 1)
				AND a.MONTH_OF_DISCHARGE_DATE = @month
		)

	UPDATE @t
	SET py_level5 =
		(
			SELECT COUNT(DISTINCT a.er_data_id)
			FROM dbo.ER_MONTHLY_DATA a WITH (NOLOCK)
				JOIN dbo.ER_MONTHLY_DATA_DETAIL b WITH (NOLOCK)
					ON a.ER_DATA_ID = b.ER_DATA_ID
						AND ((b.CHARGE_REV_CODE BETWEEN 450 AND 459) OR (b.CHARGE_REV_CODE BETWEEN 680 AND 689))

				JOIN dbo.ER_MONTHLY_DATA_DETAIL c WITH (NOLOCK)
					ON a.ER_DATA_ID = c.ER_DATA_ID
						AND c.CHARGE_HCPCS_PROC = '099285'
			WHERE a.coid = @coid
				AND a.YEAR_OF_DISCHARGE_DATE = (@year - 1)
				AND a.MONTH_OF_DISCHARGE_DATE = @month
		)

	UPDATE @t
	SET py_critical_care =
		(
			SELECT COUNT(DISTINCT a.er_data_id)
			FROM dbo.ER_MONTHLY_DATA a WITH (NOLOCK)
				JOIN dbo.ER_MONTHLY_DATA_DETAIL b WITH (NOLOCK)
					ON a.ER_DATA_ID = b.ER_DATA_ID
						AND ((b.CHARGE_REV_CODE BETWEEN 450 AND 459) OR (b.CHARGE_REV_CODE BETWEEN 680 AND 689))

				JOIN dbo.ER_MONTHLY_DATA_DETAIL c WITH (NOLOCK)
					ON a.ER_DATA_ID = c.ER_DATA_ID
						AND c.CHARGE_HCPCS_PROC IN ('099291', '099292')
			WHERE a.coid = @coid
				AND a.YEAR_OF_DISCHARGE_DATE = (@year - 1)
				AND a.MONTH_OF_DISCHARGE_DATE = @month
		)

	UPDATE @t
	SET cytd_no_level =
		(
			SELECT COUNT(DISTINCT a.er_data_id)
			FROM dbo.ER_MONTHLY_DATA a WITH (NOLOCK)
				JOIN dbo.ER_MONTHLY_DATA_DETAIL b WITH (NOLOCK)
					ON a.ER_DATA_ID = b.ER_DATA_ID
						AND ((b.CHARGE_REV_CODE BETWEEN 450 AND 459) OR (b.CHARGE_REV_CODE BETWEEN 680 AND 689))

				LEFT JOIN dbo.ER_MONTHLY_DATA_DETAIL c WITH (NOLOCK)
					ON a.ER_DATA_ID = c.ER_DATA_ID
						AND c.CHARGE_HCPCS_PROC IN ('099281', '099282', '099283', '099284', '099285', '099291', '099292')
			WHERE a.coid = @coid
				AND a.YEAR_OF_DISCHARGE_DATE = @year
				AND a.MONTH_OF_DISCHARGE_DATE <= @month
				AND c.ER_DATA_ID IS NULL
		)              
                
	UPDATE @t
	SET cytd_level1 =
		(
			SELECT COUNT(DISTINCT a.er_data_id)
			FROM dbo.ER_MONTHLY_DATA a WITH (NOLOCK)
				JOIN dbo.ER_MONTHLY_DATA_DETAIL b WITH (NOLOCK)
					ON a.ER_DATA_ID = b.ER_DATA_ID
						AND ((b.CHARGE_REV_CODE BETWEEN 450 AND 459) OR (b.CHARGE_REV_CODE BETWEEN 680 AND 689))

				JOIN dbo.ER_MONTHLY_DATA_DETAIL c WITH (NOLOCK)
					ON a.ER_DATA_ID = c.ER_DATA_ID
						AND c.CHARGE_HCPCS_PROC = '099281'
			WHERE a.coid = @coid
				AND a.YEAR_OF_DISCHARGE_DATE = @year
				AND a.MONTH_OF_DISCHARGE_DATE <= @month
		)

	UPDATE @t
	SET cytd_level2 =
		(
			SELECT COUNT(DISTINCT a.er_data_id)
			FROM dbo.ER_MONTHLY_DATA a WITH (NOLOCK)
				JOIN dbo.ER_MONTHLY_DATA_DETAIL b WITH (NOLOCK)
					ON a.ER_DATA_ID = b.ER_DATA_ID
						AND ((b.CHARGE_REV_CODE BETWEEN 450 AND 459) OR (b.CHARGE_REV_CODE BETWEEN 680 AND 689))

				JOIN dbo.ER_MONTHLY_DATA_DETAIL c WITH (NOLOCK)
					ON a.ER_DATA_ID = c.ER_DATA_ID
						AND c.CHARGE_HCPCS_PROC = '099282'
			WHERE a.coid = @coid
				AND a.YEAR_OF_DISCHARGE_DATE = @year
				AND a.MONTH_OF_DISCHARGE_DATE <= @month
		)

	UPDATE @t
	SET cytd_level3 =
		(
			SELECT COUNT(DISTINCT a.er_data_id)
			FROM dbo.ER_MONTHLY_DATA a WITH (NOLOCK)
				JOIN dbo.ER_MONTHLY_DATA_DETAIL b WITH (NOLOCK)
					ON a.ER_DATA_ID = b.ER_DATA_ID
						AND ((b.CHARGE_REV_CODE BETWEEN 450 AND 459) OR (b.CHARGE_REV_CODE BETWEEN 680 AND 689))

				JOIN dbo.ER_MONTHLY_DATA_DETAIL c WITH (NOLOCK)
					ON a.ER_DATA_ID = c.ER_DATA_ID
						AND c.CHARGE_HCPCS_PROC = '099283'
			WHERE a.coid = @coid
				AND a.YEAR_OF_DISCHARGE_DATE = @year
				AND a.MONTH_OF_DISCHARGE_DATE <= @month
		)

	UPDATE @t
	SET cytd_level4 =
		(
			SELECT COUNT(DISTINCT a.er_data_id)
			FROM dbo.ER_MONTHLY_DATA a WITH (NOLOCK)
				JOIN dbo.ER_MONTHLY_DATA_DETAIL b WITH (NOLOCK)
					ON a.ER_DATA_ID = b.ER_DATA_ID
						AND ((b.CHARGE_REV_CODE BETWEEN 450 AND 459) OR (b.CHARGE_REV_CODE BETWEEN 680 AND 689))

				JOIN dbo.ER_MONTHLY_DATA_DETAIL c WITH (NOLOCK)
					ON a.ER_DATA_ID = c.ER_DATA_ID
						AND c.CHARGE_HCPCS_PROC = '099284'
			WHERE a.coid = @coid
				AND a.YEAR_OF_DISCHARGE_DATE = @year
				AND a.MONTH_OF_DISCHARGE_DATE <= @month
		)

	UPDATE @t
	SET cytd_level5 =
		(
			SELECT COUNT(DISTINCT a.er_data_id)
			FROM dbo.ER_MONTHLY_DATA a WITH (NOLOCK)
				JOIN dbo.ER_MONTHLY_DATA_DETAIL b WITH (NOLOCK)
					ON a.ER_DATA_ID = b.ER_DATA_ID
						AND ((b.CHARGE_REV_CODE BETWEEN 450 AND 459) OR (b.CHARGE_REV_CODE BETWEEN 680 AND 689))

				JOIN dbo.ER_MONTHLY_DATA_DETAIL c WITH (NOLOCK)
					ON a.ER_DATA_ID = c.ER_DATA_ID
						AND c.CHARGE_HCPCS_PROC = '099285'
			WHERE a.coid = @coid
				AND a.YEAR_OF_DISCHARGE_DATE = @year
				AND a.MONTH_OF_DISCHARGE_DATE <= @month
		)

	UPDATE @t
	SET cytd_critical_care =
		(
			SELECT COUNT(DISTINCT a.er_data_id)
			FROM dbo.ER_MONTHLY_DATA a WITH (NOLOCK)
				JOIN dbo.ER_MONTHLY_DATA_DETAIL b WITH (NOLOCK)
					ON a.ER_DATA_ID = b.ER_DATA_ID
						AND ((b.CHARGE_REV_CODE BETWEEN 450 AND 459) OR (b.CHARGE_REV_CODE BETWEEN 680 AND 689))

				JOIN dbo.ER_MONTHLY_DATA_DETAIL c WITH (NOLOCK)
					ON a.ER_DATA_ID = c.ER_DATA_ID
						AND c.CHARGE_HCPCS_PROC IN ('099291', '099292')
			WHERE a.coid = @coid
				AND a.YEAR_OF_DISCHARGE_DATE = @year
				AND a.MONTH_OF_DISCHARGE_DATE <= @month
		)

	UPDATE @t
	SET pytd_no_level =
		(
			SELECT COUNT(DISTINCT a.er_data_id)
			FROM dbo.ER_MONTHLY_DATA a WITH (NOLOCK)
				JOIN dbo.ER_MONTHLY_DATA_DETAIL b WITH (NOLOCK)
					ON a.ER_DATA_ID = b.ER_DATA_ID
						AND ((b.CHARGE_REV_CODE BETWEEN 450 AND 459) OR (b.CHARGE_REV_CODE BETWEEN 680 AND 689))

				LEFT JOIN dbo.ER_MONTHLY_DATA_DETAIL c WITH (NOLOCK)
					ON a.ER_DATA_ID = c.ER_DATA_ID
						AND c.CHARGE_HCPCS_PROC IN ('099281', '099282', '099283', '099284', '099285', '099291', '099292')
			WHERE a.coid = @coid
				AND a.YEAR_OF_DISCHARGE_DATE = (@year - 1)
				AND a.MONTH_OF_DISCHARGE_DATE <= @month
				AND c.ER_DATA_ID IS NULL
		)              
                
	UPDATE @t
	SET pytd_level1 =
		(
			SELECT COUNT(DISTINCT a.er_data_id)
			FROM dbo.ER_MONTHLY_DATA a WITH (NOLOCK)
				JOIN dbo.ER_MONTHLY_DATA_DETAIL b WITH (NOLOCK)
					ON a.ER_DATA_ID = b.ER_DATA_ID
						AND ((b.CHARGE_REV_CODE BETWEEN 450 AND 459) OR (b.CHARGE_REV_CODE BETWEEN 680 AND 689))

				JOIN dbo.ER_MONTHLY_DATA_DETAIL c WITH (NOLOCK)
					ON a.ER_DATA_ID = c.ER_DATA_ID
						AND c.CHARGE_HCPCS_PROC = '099281'
			WHERE a.coid = @coid
				AND a.YEAR_OF_DISCHARGE_DATE = (@year - 1)
				AND a.MONTH_OF_DISCHARGE_DATE <= @month
		)

	UPDATE @t
	SET pytd_level2 =
		(
			SELECT COUNT(DISTINCT a.er_data_id)
			FROM dbo.ER_MONTHLY_DATA a WITH (NOLOCK)
				JOIN dbo.ER_MONTHLY_DATA_DETAIL b WITH (NOLOCK)
					ON a.ER_DATA_ID = b.ER_DATA_ID
						AND ((b.CHARGE_REV_CODE BETWEEN 450 AND 459) OR (b.CHARGE_REV_CODE BETWEEN 680 AND 689))

				JOIN dbo.ER_MONTHLY_DATA_DETAIL c WITH (NOLOCK)
					ON a.ER_DATA_ID = c.ER_DATA_ID
						AND c.CHARGE_HCPCS_PROC = '099282'
			WHERE a.coid = @coid
				AND a.YEAR_OF_DISCHARGE_DATE = (@year - 1)
				AND a.MONTH_OF_DISCHARGE_DATE <= @month
		)

	UPDATE @t
	SET pytd_level3 =
		(
			SELECT COUNT(DISTINCT a.er_data_id)
			FROM dbo.ER_MONTHLY_DATA a WITH (NOLOCK)
				JOIN dbo.ER_MONTHLY_DATA_DETAIL b WITH (NOLOCK)
					ON a.ER_DATA_ID = b.ER_DATA_ID
						AND ((b.CHARGE_REV_CODE BETWEEN 450 AND 459) OR (b.CHARGE_REV_CODE BETWEEN 680 AND 689))

				JOIN dbo.ER_MONTHLY_DATA_DETAIL c WITH (NOLOCK)
					ON a.ER_DATA_ID = c.ER_DATA_ID
						AND c.CHARGE_HCPCS_PROC = '099283'
			WHERE a.coid = @coid
				AND a.YEAR_OF_DISCHARGE_DATE = (@year - 1)
				AND a.MONTH_OF_DISCHARGE_DATE <= @month
		)

	UPDATE @t
	SET pytd_level4 =
		(
			SELECT COUNT(DISTINCT a.er_data_id)
			FROM dbo.ER_MONTHLY_DATA a WITH (NOLOCK)
				JOIN dbo.ER_MONTHLY_DATA_DETAIL b WITH (NOLOCK)
					ON a.ER_DATA_ID = b.ER_DATA_ID
						AND ((b.CHARGE_REV_CODE BETWEEN 450 AND 459) OR (b.CHARGE_REV_CODE BETWEEN 680 AND 689))

				JOIN dbo.ER_MONTHLY_DATA_DETAIL c WITH (NOLOCK)
					ON a.ER_DATA_ID = c.ER_DATA_ID
						AND c.CHARGE_HCPCS_PROC = '099284'
			WHERE a.coid = @coid
				AND a.YEAR_OF_DISCHARGE_DATE = (@year - 1)
				AND a.MONTH_OF_DISCHARGE_DATE <= @month
		)

	UPDATE @t
	SET pytd_level5 =
		(
			SELECT COUNT(DISTINCT a.er_data_id)
			FROM dbo.ER_MONTHLY_DATA a WITH (NOLOCK)
				JOIN dbo.ER_MONTHLY_DATA_DETAIL b WITH (NOLOCK)
					ON a.ER_DATA_ID = b.ER_DATA_ID
						AND ((b.CHARGE_REV_CODE BETWEEN 450 AND 459) OR (b.CHARGE_REV_CODE BETWEEN 680 AND 689))

				JOIN dbo.ER_MONTHLY_DATA_DETAIL c WITH (NOLOCK)
					ON a.ER_DATA_ID = c.ER_DATA_ID
						AND c.CHARGE_HCPCS_PROC = '099285'
			WHERE a.coid = @coid
				AND a.YEAR_OF_DISCHARGE_DATE = (@year - 1)
				AND a.MONTH_OF_DISCHARGE_DATE <= @month
		)

	UPDATE @t
	SET pytd_critical_care =
		(
			SELECT COUNT(DISTINCT a.er_data_id)
			FROM dbo.ER_MONTHLY_DATA a WITH (NOLOCK)
				JOIN dbo.ER_MONTHLY_DATA_DETAIL b WITH (NOLOCK)
					ON a.ER_DATA_ID = b.ER_DATA_ID
						AND ((b.CHARGE_REV_CODE BETWEEN 450 AND 459) OR (b.CHARGE_REV_CODE BETWEEN 680 AND 689))

				JOIN dbo.ER_MONTHLY_DATA_DETAIL c WITH (NOLOCK)
					ON a.ER_DATA_ID = c.ER_DATA_ID
						AND c.CHARGE_HCPCS_PROC IN ('099291', '099292')
			WHERE a.coid = @coid
				AND a.YEAR_OF_DISCHARGE_DATE = (@year - 1)
				AND a.MONTH_OF_DISCHARGE_DATE <= @month
		)

	SELECT *
	FROM @t;
END


