
CREATE PROCEDURE [dbo].[sp_Report_IGViewAdvanceData]
	(
		@worksheet_id int
	)
AS
BEGIN
	SET NOCOUNT ON;

    -- Insert statements for procedure here
	SELECT ISNULL(ADV_PAYMENT_AMT, 0) AS ADV_PAYMENT_AMT,
		ISNULL(ADVPD_NET_CHK_AMT_DUE_TO_PHYS, 0) AS ADVPD_NET_CHK_AMT_DUE_TO_PHYS,
		ISNULL(ADVPD_REMAINING_FASB_BAL, 0) AS ADVPD_REMAINING_FASB_BAL,
		ISNULL(ADVPD_HOSTFASB_BALANCE, 0) AS ADVPD_HOSTFASB_BALANCE,
		ISNULL(ADVPD_FASB_VARIANCE, 0) AS ADVPD_FASB_VARIANCE,
		ISNULL(MONTHLY_AMT, 0) AS MONTHLY_AMT,
		ISNULL(ADVPD_AMT_MARKETING_EXP, 0) AS ADVPD_AMT_MARKETING_EXP,
		ISNULL(ADVPD_AMT_RELOCATION_EXP, 0) AS ADVPD_AMT_RELOCATION_EXP,
		ISNULL(ADVPD_AMT_EDUCATION_STIPEND, 0) AS ADVPD_AMT_EDUCATION_STIPEND,
		ISNULL(ADVPD_AMT_STUDENT_LOANS, 0) AS ADVPD_AMT_STUDENT_LOANS,
		ISNULL(ADVPD_AMT_CONSULTING_COSTS, 0) AS ADVPD_AMT_CONSULTING_COSTS,
		ISNULL(ADVPD_AMT_SIGNON_BONUS, 0) AS ADVPD_AMT_SIGNON_BONUS,
		ISNULL(ADVPD_AMT_STARTUP_MISC, 0) AS ADVPD_AMT_STARTUP_MISC,
		ISNULL(ADVPD_EXPENSE_TOTAL, 0) AS ADVPD_EXPENSE_TOTAL
	FROM ig_Worksheets
	WHERE worksheet_id = @worksheet_id
END

