
CREATE PROCEDURE [dbo].[sp_Report_IGViewCashReceiptsData]
	(
		@worksheet_id int
	)
AS
BEGIN
	SET NOCOUNT ON;

    -- Insert statements for procedure here
	SELECT 
		RECEIPT_ID,
		month,
		DATE_SUBMITTED_PHYS,
		ISNULL(AMORTIZATION_AMT, 0) AS AMORTIZATION_AMT,
		ISNULL(MTH_IGNET_ADVANCES, 0) AS MTH_IGNET_ADVANCES,
		ISNULL(CASH_RECEIPTS, 0) AS CASH_RECEIPTS,
		ISNULL(MISC_CASH_RCPTS, 0) AS MISC_CASH_RCPTS,
		ISNULL(RCPTS_LESS_ADV_RECOVERIES, 0) AS RCPTS_LESS_ADV_RECOVERIES,
		ISNULL(CUR_MTH_EXCESS_COLLECTIONS, 0) AS CUR_MTH_EXCESS_COLLECTIONS,
		ISNULL(PRV_MTH_EXCESS_COLLECTIONS, 0) AS PRV_MTH_EXCESS_COLLECTIONS,
		ISNULL(CUMM_EXCESS_COLLECTIONS_MTHBEGIN, 0) AS CUMM_EXCESS_COLLECTIONS_MTHBEGIN,
		ISNULL(CUMM_EXCESS_COLLECTIONS, 0) AS CUMM_EXCESS_COLLECTIONS,
		ISNULL(EXCESS_RECOVERED_THIS_MTH_DUE, 0) AS EXCESS_RECOVERED_THIS_MTH_DUE,
		ISNULL(EXCESS_RECOVERED, 0) AS EXCESS_RECOVERED,
		ISNULL(CUMM_EXCESS_COLLECTIONS_MTHEND, 0) AS CUMM_EXCESS_COLLECTIONS_MTHEND,
		ISNULL(NET_CHK_AMT_DUE_TO_PHYS, 0) AS NET_CHK_AMT_DUE_TO_PHYS,
		ISNULL(NET_CHK_AMT_PAID_TO_PHYS, 0) AS NET_CHK_AMT_PAID_TO_PHYS,
		ISNULL(CUMM_AMT_EXCEEDING_FASB, 0) AS CUMM_AMT_EXCEEDING_FASB,
		ISNULL(REMAINING_FASB_BAL, 0) AS REMAINING_FASB_BAL,
		ISNULL(HOSTFASB_BALANCE, 0) AS HOSTFASB_BALANCE,
		ISNULL(FASB_VARIANCE, 0) AS FASB_VARIANCE,
		ISNULL(CASH_RECEIPTS, 0) AS CASH_RECEIPTS,
		ISNULL(ADJUSTMENTS, 0) AS ADJUSTMENTS,
		ISNULL(PHYS_CASH_RCPTS, 0) AS PHYS_CASH_RCPTS,
		ISNULL(COLLECTION_PERCENTAGE, 0) AS COLLECTION_PERCENTAGE,
		ISNULL(GROSS_CHARGES, 0) AS GROSS_CHARGES,
		ISNULL(TOTAL_VISITS, 0) AS TOTAL_VISITS,
		ISNULL(AR_0_30, 0) AS AR_0_30,
		ISNULL(AR_31_60, 0) AS AR_31_60,
		ISNULL(AR_61_90, 0) AS AR_61_90,
		ISNULL(AR_91_120, 0) AS AR_91_120,
		ISNULL(AR_121_150, 0) AS AR_121_150,
		ISNULL(AR_150_PLUS, 0) AS AR_150_PLUS,
		ISNULL(AR_TOTAL, 0) AS AR_TOTAL,
		ISNULL(AR_90DAYS_PERCENT, 0) AS AR_90DAYS_PERCENT,
		ISNULL(AR_VARIANCE, 0) AS AR_VARIANCE,
		CHECK_DATE,
		CHECK_NUMBER, 
		CEO_CFO_INITIALS,
		ISNULL(AMT_MARKETING_EXP, 0) AS AMT_MARKETING_EXP,
		ISNULL(AMT_RELOCATION_EXP, 0) AS AMT_RELOCATION_EXP,
		ISNULL(AMT_EDUCATION_STIPEND, 0) AS AMT_EDUCATION_STIPEND,
		ISNULL(AMT_STUDENT_LOANS, 0) AS AMT_STUDENT_LOANS,
		ISNULL(AMT_CONSULTING_COSTS, 0) AS AMT_CONSULTING_COSTS,
		ISNULL(AMT_SIGNON_BONUS, 0) AS AMT_SIGNON_BONUS,
		ISNULL(AMT_STARTUP_MISC, 0) AS AMT_STARTUP_MISC,
		ISNULL(EXPENSE_TOTAL, 0) AS EXPENSE_TOTAL
	FROM dbo.ig_Worksheet_CashRcpts
	WHERE worksheet_id = @worksheet_id
	ORDER BY month;
END

