CREATE PROCEDURE [dbo].[sp_report_ED_ActionPlans]
	(
		@coid VARCHAR(5)
	)
AS
BEGIN
	SET NOCOUNT ON;

	SELECT a.coid, 
		a.PRIORITY, 
		b.name AS category, 
		a.ED_ACTION AS ACTION, 
		c.name AS STATUS, 
		a.RESPONSIBILE_PERSON, 
		a.GOAL_TARGET_COMPLETION_DATE, 
		a.GOAL_TARGET, 
		a.BASELINE,
		d.NAME AS facility,
		(
			SELECT TOP 1 COMMENT 
			FROM dbo.ED_ACTION_PLAN_COMMENT WITH (NOLOCK) 
			WHERE ED_ACTION_PLAN_ID = a.ED_ACTION_PLAN_ID 
			ORDER BY create_date DESC
		) AS most_recent_comment
	FROM dbo.ED_ACTION_PLAN a WITH (NOLOCK)
		JOIN dbo.ED_ACTION_PLAN_CATEGORY b WITH (NOLOCK)
			ON a.ED_ACTION_PLAN_CATEGORY_ID = b.ED_ACTION_PLAN_CATEGORY_ID

		JOIN dbo.ED_ACTION_PLAN_STATUS c WITH (NOLOCK)
			ON a.ED_ACTION_PLAN_STATUS_ID = c.ED_ACTION_PLAN_STATUS_ID

		JOIN dbo.Facility d WITH (NOLOCK)
			ON a.coid = d.coid
	WHERE a.coid = @coid
		AND a.ED_ACTION_PLAN_STATUS_ID = 1
	ORDER BY c.SORT_ORDER, a.PRIORITY
END

